/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   iron-pages.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../iron-resizable-behavior/iron-resizable-behavior.d.ts" />
/// <reference path="../iron-selector/iron-selectable.d.ts" />

/**
 * `iron-pages` is used to select one of its children to show. One use is to cycle through a list of
 * children "pages".
 *
 * Example:
 *
 *     <iron-pages selected="0">
 *       <div>One</div>
 *       <div>Two</div>
 *       <div>Three</div>
 *     </iron-pages>
 *
 *     <script>
 *       document.addEventListener('click', function(e) {
 *         var pages = document.querySelector('iron-pages');
 *         pages.selectNext();
 *       });
 *     </script>
 */
interface IronPagesElement extends Polymer.Element, Polymer.IronResizableBehavior, Polymer.IronSelectableBehavior {

  /**
   * handler immediately changes it back
   */
  activateEvent: string|null|undefined;
  _selectedPageChanged(selected: any, old: any): void;
}

interface HTMLElementTagNameMap {
  "iron-pages": IronPagesElement;
}
