# Source:
# https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/flutter/cloudbuild.yaml
#
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  # Main channel
  - name: 'docker:stable'
    args: [
      'build', '.',
      '-t', 'gcr.io/$PROJECT_ID/flutter:main',
      '--build-arg', 'channel=main',
    ]
    dir: .cloud_build/flutter

  # Beta channel
  - name: 'docker:stable'
    args: [
      'build', '.',
      '-t', 'gcr.io/$PROJECT_ID/flutter:beta',
      '--build-arg', 'channel=beta',
    ]
    dir: .cloud_build/flutter

  # Stable channel
  - name: 'docker:stable'
    args: [
      'build', '.',
      '-t', 'gcr.io/$PROJECT_ID/flutter:stable',
      '-t', 'gcr.io/$PROJECT_ID/flutter',
      '--build-arg', 'channel=stable',
    ]
    dir: .cloud_build/flutter

  # Verify image runs the `flutter` command.
  - name: 'gcr.io/$PROJECT_ID/flutter'
    args: ['--help']
    dir: .cloud_build/flutter

images: [
  'gcr.io/$PROJECT_ID/flutter:main',
  'gcr.io/$PROJECT_ID/flutter:beta',
  'gcr.io/$PROJECT_ID/flutter:stable',
  'gcr.io/$PROJECT_ID/flutter',
]
tags: ['cloud-builders-community']
