image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: "open-browser"
  - port: 8082
    onOpen: "ignore"
  - port: 9501
    onOpen: "ignore"
  - port: 9502
    onOpen: "ignore"
  - port: 9503
    onOpen: "ignore"
  - port: 9504
    onOpen: "ignore"

