include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "build/**"
    - "doc/api/**"
    - "last_prod/**"
    - "lib/src/protos/**"
    - "third_party/pkg/**"
    - "web/example/workshops/**"
  errors:
    lines_longer_than_80_chars: ignore
    # TODO: Remove these ignores once dart-lang/dart-pad/issues/2467 is addressed.
    unnecessary_lambdas: ignore
    unnecessary_parenthesis: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_private_typedef_functions
    - avoid_void_async
    - directives_ordering
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_mixin
    - prefer_relative_imports
    - prefer_single_quotes
    - sort_pub_dependencies
    - unawaited_futures
    - use_enums
    - use_super_parameters
