runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 50

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 40
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  REDIS_SERVER_URI: 'redis://10.0.0.4:6379'

network:
  name: vpc-dart-services

service: default

skip_files:
- ^\.git/.*$

# Health checks, for detail please see:
# https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#updated_health_checks

# liveness_check:
#   path: "/liveness_check"
#   check_interval_sec: 30
#   timeout_sec: 5
#   failure_threshold: 2
#   success_threshold: 2
#   initial_delay_sec: 600

# readiness_check:
#   path: "/readiness_check"
#   check_interval_sec: 5
#   timeout_sec: 4
#   failure_threshold: 2
#   success_threshold: 2
#   app_start_timeout_sec: 300
