targets:
  $default:
    builders:
      # Don't clean up workshop examples, they need to be served.
      build_web_compilers:dart_source_cleanup:
        generate_for:
          exclude:
            - web/example/workshops/**.dart

      build_web_compilers|entrypoint:
        # Don't compile workshop examples.
        generate_for:
          exclude:
          - web/example/workshops/**.dart
        options:
          dart2js_args:
          - --minify
          - --fast-startup
          - -DPRE_NULL_SAFETY_SERVER_URL=https://v1.api.dartpad.dev/
          - -DNULL_SAFETY_SERVER_URL=https://nullsafety.api.dartpad.dev/
          - -DSTABLE_SERVER_URL=https://v1.api.dartpad.dev/
          - -DBETA_SERVER_URL=https://beta.api.dartpad.dev/
          - -DDEV_SERVER_URL=https://dev.api.dartpad.dev/
          - -DOLD_SERVER_URL=https://old.api.dartpad.dev/

      json_serializable:
        # Ignore workshop samples.
        generate_for:
          exclude:
          - web/example/workshops/**.dart

global_options:
  build_web_compilers:ddc:
    options:
      environment:
        PRE_NULL_SAFETY_SERVER_URL: https://v1.api.dartpad.dev/
        NULL_SAFETY_SERVER_URL: https://nullsafety.api.dartpad.dev/
        STABLE_SERVER_URL: https://nullsafety.api.dartpad.dev/
        BETA_SERVER_URL: https://beta.api.dartpad.dev/
        DEV_SERVER_URL: https://dev.api.dartpad.dev/
        OLD_SERVER_URL: https://old.api.dartpad.dev/