targets:
  $default:
    builders:
      # Don't clean up workshop examples, they need to be served.
      build_web_compilers:dart_source_cleanup:
        generate_for:
          exclude:
            - web/example/workshops/**.dart

      build_web_compilers|entrypoint:
        # Don't compile workshop examples.
        generate_for:
          exclude:
          - web/example/workshops/**.dart
        options:
          dart2js_args:
          - --fast-startup
          - --minify
          - --no-source-maps
          - -DSERVER_URL=https://stable.api.dartpad.dev/
          - -DSTABLE_SERVER_URL=https://stable.api.dartpad.dev/
          - -DBETA_SERVER_URL=https://beta.api.dartpad.dev/
          - -DDEV_SERVER_URL=https://dev.api.dartpad.dev/
          - -DOLD_SERVER_URL=https://old.api.dartpad.dev/
          - -DGH_AUTH_INIT_BASE_URL=https://githubauth-brsyns7rna-uw.a.run.app
          #Should be GitHub Init OAuth end point on Google Cloud Run
          #- -DGH_AUTH_INIT_BASE_URL=https://localhost:8080/initiate/
          
      json_serializable:
        # Ignore workshop samples.
        generate_for:
          exclude:
          - web/example/workshops/**.dart

global_options:
  build_web_compilers:ddc:
    options:
      environment:
        SERVER_URL: https://stable.api.dartpad.dev/
        STABLE_SERVER_URL: https://stable.api.dartpad.dev/
        BETA_SERVER_URL: https://beta.api.dartpad.dev/
        DEV_SERVER_URL: https://dev.api.dartpad.dev/
        OLD_SERVER_URL: https://old.api.dartpad.dev/
        GH_AUTH_INIT_BASE_URL: https://githubauth-brsyns7rna-uw.a.run.app
        #Should be GitHub Init OAuth end point on Google Cloud Run
        #GH_AUTH_INIT_BASE_URL: https://localhost:8080/initiate/