include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - flutter-sdks/**
    - local_pub_cache/**
    - project_templates/**
  errors:
    lines_longer_than_80_chars: ignore
    unreachable_from_main: ignore
    # Remove this once we remove the AnalysisIssue.sourceName field.
    deprecated_member_use_from_same_package: ignore

linter:
  rules:
    - prefer_final_in_for_each
    - prefer_final_locals
