include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - flutter-sdks/**
    - local_pub_cache/**
    - project_templates/**
  errors:
    lines_longer_than_80_chars: ignore

linter:
  rules:
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
