name: dart_pad
description: The front end of DartPad.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  async: ^2.11.0
  checked_yaml: ^2.0.3
  codemirror: ^0.7.10+5.65.13
  collection: ^1.17.2
  encrypt: ^5.0.1
  fluttering_phrases: ^0.5.0
  html_unescape: ^2.0.0
  http: ^0.13.0
  js: ^0.6.7
  json_annotation: ^4.8.0
  logging: ^1.2.0
  markdown: ^7.0.1
  mdc_web: ^0.6.0
  meta: ^1.8.0
  path: ^1.8.0
  protobuf: ^3.0.0
  pub_semver: ^2.1.0
  sass_builder: ^2.2.1
  shelf: ^1.3.0
  shelf_static: ^1.1.0
  split: any
  stream_transform: ^2.0.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.4
  build_test: ^2.1.7
  build_web_compilers: ^4.0.3
  dart_flutter_team_lints: ^2.0.0
  git: ^2.0.0
  grinder: ^0.9.4
  json_serializable: ^6.7.0
  test: ^1.21.1
  webdriver: ^3.0.2

dependency_overrides:
  # package:mdc_web needs to upgrade the version of material-components-web 12.0.0
  # or above, which includes this fix for the division operator:
  # https://github.com/material-components/material-components-web/pull/7158
  #
  # Until then, dart-sass produces a warning that this operator is being removed
  # in favor of calc().
  #
  # See this issue for details:
  # https://github.com/dart-lang/dart-pad/issues/2388
  sass: ^1.62.0

  split:
    path: third_party/pkg/split/
