name: codemirror_lang_dart
description: Dart language support for CodeMirror 6 using the Dart analyzer.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.12.0-0

resolution: workspace

dependencies:
  analyzer: ^12.1.0
  web: ^1.1.1

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
