// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// This file has been automatically generated by
// `pkgs/dartpad_preview/examples/build_examples.dart` - please do not edit it manually.

import 'example.dart';
export 'example.dart';

abstract final class Examples {
  static const List<Example> all = [
    _dart,
    _flutter,
    _fibonacci,
    _counter,
    _sunflower,
    _flameGame,
  ];

  static Example? getById(String id) {
    for (final example in all) {
      if (example.id == id) {
        return example;
      }
    }
    return null;
  }

  static const Example defaultExample = _counter;
}

const _dart = Example(
  name: 'Dart Snippet',
  id: 'dart',
  icon: 'images/dart_logo_192.png',
  archivePath: 'examples/dart.tar.gz',
  entryPath: 'lib/main.dart',
);
const _flutter = Example(
  name: 'Flutter Snippet',
  id: 'flutter',
  icon: 'images/flutter_logo_192.png',
  archivePath: 'examples/flutter.tar.gz',
  entryPath: 'lib/main.dart',
);
const _fibonacci = Example(
  name: 'Fibonacci',
  id: 'fibonacci',
  subcategory: 'Dart',
  icon: 'images/dart_logo_192.png',
  archivePath: 'examples/fibonacci.tar.gz',
  entryPath: 'lib/main.dart',
);
const _counter = Example(
  name: 'Counter',
  id: 'counter',
  subcategory: 'Flutter',
  icon: 'images/flutter_logo_192.png',
  archivePath: 'examples/counter.tar.gz',
  entryPath: 'lib/main.dart',
);
const _sunflower = Example(
  name: 'Sunflower',
  id: 'sunflower',
  subcategory: 'Flutter',
  icon: 'images/flutter_logo_192.png',
  archivePath: 'examples/sunflower.tar.gz',
  entryPath: 'lib/main.dart',
);
const _flameGame = Example(
  name: 'Flame Game',
  id: 'flame-game',
  subcategory: 'Flutter',
  icon: 'images/flutter_logo_192.png',
  archivePath: 'examples/flame-game.tar.gz',
  entryPath: 'lib/main.dart',
);
