// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// This file has been automatically generated by
// `pkgs/dartpad_preview/examples/build_examples.dart` - please do not edit it manually.

import 'example.dart';
export 'example.dart';

abstract final class Examples {
  static const List<Example> snippets = [
    _dart,
    _flutter,
  ];

  static const List<Example> samples = [
    _counter,
    _fibonacci,
    _flameGame,
    _helloWorld,
    _sunflower,
  ];

  static const List<Example> all = [
    _dart,
    _flutter,
    _counter,
    _fibonacci,
    _flameGame,
    _helloWorld,
    _sunflower,
  ];

  static Example? getById(String id) {
    for (final example in all) {
      if (example.id == id) {
        return example;
      }
    }
    return null;
  }

  static const Example defaultExample = _counter;
}

const _dart = Example(
  name: 'Dart snippet',
  id: 'dart',
  archivePath: 'examples/dart.tar.gz',
  entryPath: 'lib/main.dart',
);

const _flutter = Example(
  name: 'Flutter snippet',
  id: 'flutter',
  archivePath: 'examples/flutter.tar.gz',
  entryPath: 'lib/main.dart',
);

const _counter = Example(
  name: 'Counter',
  id: 'counter',
  archivePath: 'examples/counter.tar.gz',
  entryPath: 'lib/main.dart',
);

const _fibonacci = Example(
  name: 'Fibonacci',
  id: 'fibonacci',
  archivePath: 'examples/fibonacci.tar.gz',
  entryPath: 'lib/main.dart',
);

const _flameGame = Example(
  name: 'Flame game',
  id: 'flame-game',
  archivePath: 'examples/flame-game.tar.gz',
  entryPath: 'lib/main.dart',
);

const _helloWorld = Example(
  name: 'Hello world',
  id: 'hello-world',
  archivePath: 'examples/hello-world.tar.gz',
  entryPath: 'lib/main.dart',
);

const _sunflower = Example(
  name: 'Sunflower',
  id: 'sunflower',
  archivePath: 'examples/sunflower.tar.gz',
  entryPath: 'lib/main.dart',
);
