include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  exclude:
    - "**/node_modules/**"
    - "**/build/**"
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-raw-types: true

# Jaspr has a custom analyzer plugin 'jaspr_lints', which is enabled here.
# Plugins can only be specified at the workspace root.
plugins:
  jaspr_lints:
    version: ^0.7.1
    diagnostics:
      prefer_html_components: true
      sort_children_last: true
      styles_ordering: true
      unsafe_imports: false # TODO: Enable once version 0.8.0 is released.

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    always_put_control_body_on_new_line: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    matching_super_parameters: true
    no_literal_bool_comparisons: true
    unnecessary_breaks: true
    unnecessary_ignore: true
    unnecessary_null_checks: true
