# Workspace for DartPad preview packages.
# This is intentionally separate from the top-level dartpad workspace
# to avoid being constrained by its potentially outdated dependencies.
name: dartpad_preview_workspace
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - codemirror-lang-dart
  - codemirror-dart
  - packages/dartpad_preview_shared

environment:
  sdk: ^3.12.0-0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
