# Workspace for DartPad preview packages.
# This is intentionally separate from the top-level dartpad workspace
# to avoid being constrained by its potentially outdated dependencies.
name: dartpad_preview_workspace
publish_to: none

workspace:
  - codemirror-lang-dart
  - codemirror-dart
  - dartpad_preview_shared

environment:
  sdk: ^3.12.0-0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2

dependency_overrides:
  dartpad:
    git:
      url: https://github.com/dart-lang/sdk
      path: pkg/dartpad
      ref: 064fcb01ba7e08a2179a28146801df49341188e4
