
var CanvasKitInit = (() => {
  var _scriptName = import.meta.url;
  
  return (
function(moduleArg = {}) {
  var moduleRtn;

var q=moduleArg,aa,ca,da=new Promise((a,b)=>{aa=a;ca=b}),ea="object"==typeof window,fa="function"==typeof importScripts;
(function(a){a.Fd=a.Fd||[];a.Fd.push(function(){a.MakeSWCanvasSurface=function(b){var c=b,e="undefined"!==typeof OffscreenCanvas&&c instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&c instanceof HTMLCanvasElement||e||(c=document.getElementById(b),c)))throw"Canvas with id "+b+" was not found";if(b=a.MakeSurface(c.width,c.height))b.ce=c;return b};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(b,c){var e={width:b,height:c,colorType:a.ColorType.RGBA_8888,
alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},f=b*c*4,h=a._malloc(f);if(e=a.Surface._makeRasterDirect(e,h,4*b))e.ce=null,e.Ce=b,e.ze=c,e.Ae=f,e.je=h,e.getCanvas().clear(a.TRANSPARENT);return e};a.MakeRasterDirectSurface=function(b,c,e){return a.Surface._makeRasterDirect(b,c.byteOffset,e)};a.Surface.prototype.flush=function(b){a.Cd(this.Bd);this._flush();if(this.ce){var c=new Uint8ClampedArray(a.HEAPU8.buffer,this.je,this.Ae);c=new ImageData(c,this.Ce,this.ze);b?this.ce.getContext("2d").putImageData(c,
0,0,b[0],b[1],b[2]-b[0],b[3]-b[1]):this.ce.getContext("2d").putImageData(c,0,0)}};a.Surface.prototype.dispose=function(){this.je&&a._free(this.je);this.delete()};a.Cd=a.Cd||function(){};a.de=a.de||function(){return null}})})(q);
(function(a){a.Fd=a.Fd||[];a.Fd.push(function(){function b(k,p,t){return k&&k.hasOwnProperty(p)?k[p]:t}function c(k){var p=ha(ia);ia[p]=k;return p}function e(k){return k.naturalHeight||k.videoHeight||k.displayHeight||k.height}function f(k){return k.naturalWidth||k.videoWidth||k.displayWidth||k.width}function h(k,p,t,v){k.bindTexture(k.TEXTURE_2D,p);v||t.alphaType!==a.AlphaType.Premul||k.pixelStorei(k.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);return p}function n(k,p,t){t||p.alphaType!==a.AlphaType.Premul||
k.pixelStorei(k.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);k.bindTexture(k.TEXTURE_2D,null)}a.GetWebGLContext=function(k,p){if(!k)throw"null canvas passed into makeWebGLContext";var t={alpha:b(p,"alpha",1),depth:b(p,"depth",1),stencil:b(p,"stencil",8),antialias:b(p,"antialias",0),premultipliedAlpha:b(p,"premultipliedAlpha",1),preserveDrawingBuffer:b(p,"preserveDrawingBuffer",0),preferLowPowerToHighPerformance:b(p,"preferLowPowerToHighPerformance",0),failIfMajorPerformanceCaveat:b(p,"failIfMajorPerformanceCaveat",
0),enableExtensionsByDefault:b(p,"enableExtensionsByDefault",1),explicitSwapControl:b(p,"explicitSwapControl",0),renderViaOffscreenBackBuffer:b(p,"renderViaOffscreenBackBuffer",0)};t.majorVersion=p&&p.majorVersion?p.majorVersion:"undefined"!==typeof WebGL2RenderingContext?2:1;if(t.explicitSwapControl)throw"explicitSwapControl is not supported";k=ja(k,t);if(!k)return 0;ka(k);x.Od.getExtension("WEBGL_debug_renderer_info");return k};a.deleteContext=function(k){x===la[k]&&(x=null);"object"==typeof JSEvents&&
JSEvents.af(la[k].Od.canvas);la[k]&&la[k].Od.canvas&&(la[k].Od.canvas.xe=void 0);la[k]=null};a._setTextureCleanup({deleteTexture:function(k,p){var t=ia[p];t&&la[k].Od.deleteTexture(t);ia[p]=null}});a.MakeWebGLContext=function(k){if(!this.Cd(k))return null;var p=this._MakeGrContext();if(!p)return null;p.Bd=k;var t=p.delete.bind(p);p["delete"]=function(){a.Cd(this.Bd);t()}.bind(p);return x.le=p};a.MakeGrContext=a.MakeWebGLContext;a.GrDirectContext.prototype.getResourceCacheLimitBytes=function(){a.Cd(this.Bd);
this._getResourceCacheLimitBytes()};a.GrDirectContext.prototype.getResourceCacheUsageBytes=function(){a.Cd(this.Bd);this._getResourceCacheUsageBytes()};a.GrDirectContext.prototype.releaseResourcesAndAbandonContext=function(){a.Cd(this.Bd);this._releaseResourcesAndAbandonContext()};a.GrDirectContext.prototype.setResourceCacheLimitBytes=function(k){a.Cd(this.Bd);this._setResourceCacheLimitBytes(k)};a.MakeOnScreenGLSurface=function(k,p,t,v,z,A){if(!this.Cd(k.Bd))return null;p=void 0===z||void 0===A?
this._MakeOnScreenGLSurface(k,p,t,v):this._MakeOnScreenGLSurface(k,p,t,v,z,A);if(!p)return null;p.Bd=k.Bd;return p};a.MakeRenderTarget=function(){var k=arguments[0];if(!this.Cd(k.Bd))return null;if(3===arguments.length){var p=this._MakeRenderTargetWH(k,arguments[1],arguments[2]);if(!p)return null}else if(2===arguments.length){if(p=this._MakeRenderTargetII(k,arguments[1]),!p)return null}else return null;p.Bd=k.Bd;return p};a.MakeWebGLCanvasSurface=function(k,p,t){p=p||null;var v=k,z="undefined"!==
typeof OffscreenCanvas&&v instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&v instanceof HTMLCanvasElement||z||(v=document.getElementById(k),v)))throw"Canvas with id "+k+" was not found";k=this.GetWebGLContext(v,t);if(!k||0>k)throw"failed to create webgl context: err "+k;k=this.MakeWebGLContext(k);p=this.MakeOnScreenGLSurface(k,v.width,v.height,p);return p?p:(p=v.cloneNode(!0),v.parentNode.replaceChild(p,v),p.classList.add("ck-replaced"),a.MakeSWCanvasSurface(p))};a.MakeCanvasSurface=
a.MakeWebGLCanvasSurface;a.Surface.prototype.makeImageFromTexture=function(k,p){a.Cd(this.Bd);k=c(k);if(p=this._makeImageFromTexture(this.Bd,k,p))p.Xd=k;return p};a.Surface.prototype.makeImageFromTextureSource=function(k,p,t){p||={height:e(k),width:f(k),colorType:a.ColorType.RGBA_8888,alphaType:t?a.AlphaType.Premul:a.AlphaType.Unpremul};p.colorSpace||(p.colorSpace=a.ColorSpace.SRGB);a.Cd(this.Bd);var v=x.Od;t=h(v,v.createTexture(),p,t);2===x.version?v.texImage2D(v.TEXTURE_2D,0,v.RGBA,p.width,p.height,
0,v.RGBA,v.UNSIGNED_BYTE,k):v.texImage2D(v.TEXTURE_2D,0,v.RGBA,v.RGBA,v.UNSIGNED_BYTE,k);n(v,p);this._resetContext();return this.makeImageFromTexture(t,p)};a.Surface.prototype.updateTextureFromSource=function(k,p,t){if(k.Xd){a.Cd(this.Bd);var v=k.getImageInfo(),z=x.Od,A=h(z,ia[k.Xd],v,t);2===x.version?z.texImage2D(z.TEXTURE_2D,0,z.RGBA,f(p),e(p),0,z.RGBA,z.UNSIGNED_BYTE,p):z.texImage2D(z.TEXTURE_2D,0,z.RGBA,z.RGBA,z.UNSIGNED_BYTE,p);n(z,v,t);this._resetContext();ia[k.Xd]=null;k.Xd=c(A);v.colorSpace=
k.getColorSpace();p=this._makeImageFromTexture(this.Bd,k.Xd,v);t=k.Ad.Dd;z=k.Ad.Hd;k.Ad.Dd=p.Ad.Dd;k.Ad.Hd=p.Ad.Hd;p.Ad.Dd=t;p.Ad.Hd=z;p.delete();v.colorSpace.delete()}};a.MakeLazyImageFromTextureSource=function(k,p,t){p||={height:e(k),width:f(k),colorType:a.ColorType.RGBA_8888,alphaType:t?a.AlphaType.Premul:a.AlphaType.Unpremul};p.colorSpace||(p.colorSpace=a.ColorSpace.SRGB);var v={makeTexture:function(){var z=x,A=z.Od,E=h(A,A.createTexture(),p,t);2===z.version?A.texImage2D(A.TEXTURE_2D,0,A.RGBA,
p.width,p.height,0,A.RGBA,A.UNSIGNED_BYTE,k):A.texImage2D(A.TEXTURE_2D,0,A.RGBA,A.RGBA,A.UNSIGNED_BYTE,k);n(A,p,t);return c(E)},freeSrc:function(){}};"VideoFrame"===k.constructor.name&&(v.freeSrc=function(){k.close()});return a.Image._makeFromGenerator(p,v)};a.Cd=function(k){return k?ka(k):!1};a.de=function(){return x&&x.le&&!x.le.isDeleted()?x.le:null}})})(q);
(function(a){function b(l){return(f(255*l[3])<<24|f(255*l[0])<<16|f(255*l[1])<<8|f(255*l[2])<<0)>>>0}function c(l){if(l&&l._ck)return l;if(l instanceof Float32Array){for(var d=Math.floor(l.length/4),g=new Uint32Array(d),m=0;m<d;m++)g[m]=b(l.slice(4*m,4*(m+1)));return g}if(l instanceof Uint32Array)return l;if(l instanceof Array&&l[0]instanceof Float32Array)return l.map(b)}function e(l){if(void 0===l)return 1;var d=parseFloat(l);return l&&-1!==l.indexOf("%")?d/100:d}function f(l){return Math.round(Math.max(0,
Math.min(l||0,255)))}function h(l,d){d&&d._ck||a._free(l)}function n(l,d,g){if(!l||!l.length)return 0;if(l&&l._ck)return l.byteOffset;var m=a[d].BYTES_PER_ELEMENT;g||=a._malloc(l.length*m);a[d].set(l,g/m);return g}function k(l){var d={Md:0,count:l.length,colorType:a.ColorType.RGBA_F32};if(l instanceof Float32Array)d.Md=n(l,"HEAPF32"),d.count=l.length/4;else if(l instanceof Uint32Array)d.Md=n(l,"HEAPU32"),d.colorType=a.ColorType.RGBA_8888;else if(l instanceof Array){if(l&&l.length){for(var g=a._malloc(16*
l.length),m=0,r=g/4,u=0;u<l.length;u++)for(var w=0;4>w;w++)a.HEAPF32[r+m]=l[u][w],m++;l=g}else l=0;d.Md=l}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof l;return d}function p(l){if(!l)return 0;var d=V.toTypedArray();if(l.length){if(6===l.length||9===l.length)return n(l,"HEAPF32",L),6===l.length&&a.HEAPF32.set(Oc,6+L/4),L;if(16===l.length)return d[0]=l[0],d[1]=l[1],d[2]=l[3],d[3]=l[4],d[4]=l[5],d[5]=l[7],d[6]=l[12],d[7]=l[13],d[8]=l[15],L;throw"invalid matrix size";
}if(void 0===l.m11)throw"invalid matrix argument";d[0]=l.m11;d[1]=l.m21;d[2]=l.m41;d[3]=l.m12;d[4]=l.m22;d[5]=l.m42;d[6]=l.m14;d[7]=l.m24;d[8]=l.m44;return L}function t(l){if(!l)return 0;var d=S.toTypedArray();if(l.length){if(16!==l.length&&6!==l.length&&9!==l.length)throw"invalid matrix size";if(16===l.length)return n(l,"HEAPF32",ba);d.fill(0);d[0]=l[0];d[1]=l[1];d[3]=l[2];d[4]=l[3];d[5]=l[4];d[7]=l[5];d[10]=1;d[12]=l[6];d[13]=l[7];d[15]=l[8];6===l.length&&(d[12]=0,d[13]=0,d[15]=1);return ba}if(void 0===
l.m11)throw"invalid matrix argument";d[0]=l.m11;d[1]=l.m21;d[2]=l.m31;d[3]=l.m41;d[4]=l.m12;d[5]=l.m22;d[6]=l.m32;d[7]=l.m42;d[8]=l.m13;d[9]=l.m23;d[10]=l.m33;d[11]=l.m43;d[12]=l.m14;d[13]=l.m24;d[14]=l.m34;d[15]=l.m44;return ba}function v(l,d){return n(l,"HEAPF32",d||X)}function z(l,d,g,m){var r=ya.toTypedArray();r[0]=l;r[1]=d;r[2]=g;r[3]=m;return X}function A(l){for(var d=new Float32Array(4),g=0;4>g;g++)d[g]=a.HEAPF32[l/4+g];return d}function E(l,d){return n(l,"HEAPF32",d||P)}function M(l,d){return n(l,
"HEAPF32",d||ob)}a.Color=function(l,d,g,m){void 0===m&&(m=1);return a.Color4f(f(l)/255,f(d)/255,f(g)/255,m)};a.ColorAsInt=function(l,d,g,m){void 0===m&&(m=255);return(f(m)<<24|f(l)<<16|f(d)<<8|f(g)<<0&268435455)>>>0};a.Color4f=function(l,d,g,m){void 0===m&&(m=1);return Float32Array.of(l,d,g,m)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,
1,1,1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(l){return[Math.floor(255*
l[0]),Math.floor(255*l[1]),Math.floor(255*l[2]),l[3]]};a.parseColorString=function(l,d){l=l.toLowerCase();if(l.startsWith("#")){d=255;switch(l.length){case 9:d=parseInt(l.slice(7,9),16);case 7:var g=parseInt(l.slice(1,3),16);var m=parseInt(l.slice(3,5),16);var r=parseInt(l.slice(5,7),16);break;case 5:d=17*parseInt(l.slice(4,5),16);case 4:g=17*parseInt(l.slice(1,2),16),m=17*parseInt(l.slice(2,3),16),r=17*parseInt(l.slice(3,4),16)}return a.Color(g,m,r,d/255)}return l.startsWith("rgba")?(l=l.slice(5,
-1),l=l.split(","),a.Color(+l[0],+l[1],+l[2],e(l[3]))):l.startsWith("rgb")?(l=l.slice(4,-1),l=l.split(","),a.Color(+l[0],+l[1],+l[2],e(l[3]))):l.startsWith("gray(")||l.startsWith("hsl")||!d||(l=d[l],void 0===l)?a.BLACK:l};a.multiplyByAlpha=function(l,d){l=l.slice();l[3]=Math.max(0,Math.min(l[3]*d,1));return l};a.Malloc=function(l,d){var g=a._malloc(d*l.BYTES_PER_ELEMENT);return{_ck:!0,length:d,byteOffset:g,Td:null,subarray:function(m,r){m=this.toTypedArray().subarray(m,r);m._ck=!0;return m},toTypedArray:function(){if(this.Td&&
this.Td.length)return this.Td;this.Td=new l(a.HEAPU8.buffer,g,d);this.Td._ck=!0;return this.Td}}};a.Free=function(l){a._free(l.byteOffset);l.byteOffset=0;l.toTypedArray=null;l.Td=null};var L=0,V,ba=0,S,X=0,ya,W,P=0,Mb,ra=0,Nb,pb=0,Ob,qb=0,Va,Ga=0,Pb,ob=0,Qb,Rb=0,Oc=Float32Array.of(0,0,1);a.onRuntimeInitialized=function(){function l(d,g,m,r,u,w,B){w||(w=4*r.width,r.colorType===a.ColorType.RGBA_F16?w*=2:r.colorType===a.ColorType.RGBA_F32&&(w*=4));var J=w*r.height;var F=u?u.byteOffset:a._malloc(J);if(B?
!d._readPixels(r,F,w,g,m,B):!d._readPixels(r,F,w,g,m))return u||a._free(F),null;if(u)return u.toTypedArray();switch(r.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:d=(new Uint8Array(a.HEAPU8.buffer,F,J)).slice();break;case a.ColorType.RGBA_F32:d=(new Float32Array(a.HEAPU8.buffer,F,J)).slice();break;default:return null}a._free(F);return d}ya=a.Malloc(Float32Array,4);X=ya.byteOffset;S=a.Malloc(Float32Array,16);ba=S.byteOffset;V=a.Malloc(Float32Array,9);L=V.byteOffset;Pb=a.Malloc(Float32Array,
12);ob=Pb.byteOffset;Qb=a.Malloc(Float32Array,12);Rb=Qb.byteOffset;W=a.Malloc(Float32Array,4);P=W.byteOffset;Mb=a.Malloc(Float32Array,4);ra=Mb.byteOffset;Nb=a.Malloc(Float32Array,3);pb=Nb.byteOffset;Ob=a.Malloc(Float32Array,3);qb=Ob.byteOffset;Va=a.Malloc(Int32Array,4);Ga=Va.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(d){var g=n(d,"HEAPF32"),m=a.Path._MakeFromCmds(g,d.length);h(g,d);return m};a.Path.MakeFromVerbsPointsWeights=function(d,g,m){var r=n(d,"HEAPU8"),u=n(g,"HEAPF32"),w=n(m,"HEAPF32"),B=a.Path._MakeFromVerbsPointsWeights(r,d.length,u,g.length/2,w,m&&m.length||0);h(r,d);h(u,g);h(w,m);return B};a.PathBuilder.prototype.addArc=function(d,g,m){d=E(d);this._addArc(d,g,m);return this};a.PathBuilder.prototype.addCircle=function(d,g,m,r){this._addCircle(d,g,m,!!r);return this};a.PathBuilder.prototype.addOval=
function(d,g,m){void 0===m&&(m=1);d=E(d);this._addOval(d,!!g,m);return this};a.PathBuilder.prototype.addPath=function(){var d=Array.prototype.slice.call(arguments),g=d[0],m=!1;"boolean"===typeof d[d.length-1]&&(m=d.pop());if(1===d.length)this._addPath(g,1,0,0,0,1,0,0,0,1,m);else if(2===d.length)d=d[1],this._addPath(g,d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1,m);else if(7===d.length||10===d.length)this._addPath(g,d[1],d[2],d[3],d[4],d[5],d[6],d[7]||0,d[8]||0,d[9]||1,m);else return null;
return this};a.PathBuilder.prototype.addPolygon=function(d,g){var m=n(d,"HEAPF32");this._addPolygon(m,d.length/2,g);h(m,d);return this};a.PathBuilder.prototype.addRect=function(d,g){d=E(d);this._addRect(d,!!g);return this};a.PathBuilder.prototype.addRRect=function(d,g){d=M(d);this._addRRect(d,!!g);return this};a.PathBuilder.prototype.addVerbsPointsWeights=function(d,g,m){var r=n(d,"HEAPU8"),u=n(g,"HEAPF32"),w=n(m,"HEAPF32");this._addVerbsPointsWeights(r,d.length,u,g.length/2,w,m&&m.length||0);h(r,
d);h(u,g);h(w,m);return this};a.PathBuilder.prototype.arc=function(d,g,m,r,u,w){d=a.LTRBRect(d-m,g-m,d+m,g+m);u=(u-r)/Math.PI*180-360*!!w;r=(new a.PathBuilder).addArc(d,r/Math.PI*180,u).detachAndDelete();this.addPath(r,!0);r.delete();return this};a.PathBuilder.prototype.arcToOval=function(d,g,m,r){d=E(d);this._arcToOval(d,g,m,r);return this};a.PathBuilder.prototype.arcToRotated=function(d,g,m,r,u,w,B){this._arcToRotated(d,g,m,!!r,!!u,w,B);return this};a.PathBuilder.prototype.arcToTangent=function(d,
g,m,r,u){this._arcToTangent(d,g,m,r,u);return this};a.PathBuilder.prototype.close=function(){this._close();return this};a.PathBuilder.prototype.conicTo=function(d,g,m,r,u){this._conicTo(d,g,m,r,u);return this};a.Path.prototype.computeTightBounds=function(d){this._computeTightBounds(P);var g=W.toTypedArray();return d?(d.set(g),d):g.slice()};a.PathBuilder.prototype.cubicTo=function(d,g,m,r,u,w){this._cubicTo(d,g,m,r,u,w);return this};a.PathBuilder.prototype.detachAndDelete=function(){var d=this.detach();
this.delete();return d};a.Path.prototype.getBounds=function(d){this._getBounds(P);var g=W.toTypedArray();return d?(d.set(g),d):g.slice()};a.PathBuilder.prototype.getBounds=function(d){this._getBounds(P);var g=W.toTypedArray();return d?(d.set(g),d):g.slice()};a.PathBuilder.prototype.lineTo=function(d,g){this._lineTo(d,g);return this};a.PathBuilder.prototype.moveTo=function(d,g){this._moveTo(d,g);return this};a.PathBuilder.prototype.offset=function(d,g){this._transform(1,0,d,0,1,g,0,0,1);return this};
a.PathBuilder.prototype.quadTo=function(d,g,m,r){this._quadTo(d,g,m,r);return this};a.PathBuilder.prototype.rArcTo=function(d,g,m,r,u,w,B){this._rArcTo(d,g,m,r,u,w,B);return this};a.PathBuilder.prototype.rConicTo=function(d,g,m,r,u){this._rConicTo(d,g,m,r,u);return this};a.PathBuilder.prototype.rCubicTo=function(d,g,m,r,u,w){this._rCubicTo(d,g,m,r,u,w);return this};a.PathBuilder.prototype.rLineTo=function(d,g){this._rLineTo(d,g);return this};a.PathBuilder.prototype.rMoveTo=function(d,g){this._rMoveTo(d,
g);return this};a.PathBuilder.prototype.rQuadTo=function(d,g,m,r){this._rQuadTo(d,g,m,r);return this};a.Path.prototype.makeStroked=function(d){d=d||{};d.width=d.width||1;d.miter_limit=d.miter_limit||4;d.cap=d.cap||a.StrokeCap.Butt;d.join=d.join||a.StrokeJoin.Miter;d.precision=d.precision||1;return this._makeStroked(d)};a.PathBuilder.prototype.transform=function(){if(1===arguments.length){var d=arguments[0];this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1)}else if(6===arguments.length||
9===arguments.length)d=arguments,this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.makeTrimmed=function(d,g,m){return this._makeTrimmed(d,g,!!m)};a.Image.prototype.encodeToBytes=function(d,g){var m=a.de();d=d||a.ImageFormat.PNG;g=g||100;return m?this._encodeToBytes(d,g,m):this._encodeToBytes(d,g)};a.Image.prototype.makeShaderCubic=function(d,g,m,r,u){u=p(u);return this._makeShaderCubic(d,
g,m,r,u)};a.Image.prototype.makeShaderOptions=function(d,g,m,r,u){u=p(u);return this._makeShaderOptions(d,g,m,r,u)};a.Image.prototype.readPixels=function(d,g,m,r,u){var w=a.de();return l(this,d,g,m,r,u,w)};a.Canvas.prototype.clear=function(d){a.Cd(this.Bd);d=v(d);this._clear(d)};a.Canvas.prototype.clipRRect=function(d,g,m){a.Cd(this.Bd);d=M(d);this._clipRRect(d,g,m)};a.Canvas.prototype.clipRect=function(d,g,m){a.Cd(this.Bd);d=E(d);this._clipRect(d,g,m)};a.Canvas.prototype.concat=function(d){a.Cd(this.Bd);
d=t(d);this._concat(d)};a.Canvas.prototype.drawArc=function(d,g,m,r,u){a.Cd(this.Bd);d=E(d);this._drawArc(d,g,m,r,u)};a.Canvas.prototype.drawAtlas=function(d,g,m,r,u,w,B){if(d&&r&&g&&m&&g.length===m.length){a.Cd(this.Bd);u||(u=a.BlendMode.SrcOver);var J=n(g,"HEAPF32"),F=n(m,"HEAPF32"),R=m.length/4,T=n(c(w),"HEAPU32");if(B&&"B"in B&&"C"in B)this._drawAtlasCubic(d,F,J,T,R,u,B.B,B.C,r);else{let sa=a.FilterMode.Linear,Ha=a.MipmapMode.None;B&&(sa=B.filter,"mipmap"in B&&(Ha=B.mipmap));this._drawAtlasOptions(d,
F,J,T,R,u,sa,Ha,r)}h(J,g);h(F,m);h(T,w)}};a.Canvas.prototype.drawCircle=function(d,g,m,r){a.Cd(this.Bd);this._drawCircle(d,g,m,r)};a.Canvas.prototype.drawColor=function(d,g){a.Cd(this.Bd);d=v(d);void 0!==g?this._drawColor(d,g):this._drawColor(d)};a.Canvas.prototype.drawColorInt=function(d,g){a.Cd(this.Bd);this._drawColorInt(d,g||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=function(d,g,m,r,u){a.Cd(this.Bd);d=z(d,g,m,r);void 0!==u?this._drawColor(d,u):this._drawColor(d)};a.Canvas.prototype.drawDRRect=
function(d,g,m){a.Cd(this.Bd);d=M(d,ob);g=M(g,Rb);this._drawDRRect(d,g,m)};a.Canvas.prototype.drawImage=function(d,g,m,r){a.Cd(this.Bd);this._drawImage(d,g,m,r||null)};a.Canvas.prototype.drawImageCubic=function(d,g,m,r,u,w){a.Cd(this.Bd);this._drawImageCubic(d,g,m,r,u,w||null)};a.Canvas.prototype.drawImageOptions=function(d,g,m,r,u,w){a.Cd(this.Bd);this._drawImageOptions(d,g,m,r,u,w||null)};a.Canvas.prototype.drawImageNine=function(d,g,m,r,u){a.Cd(this.Bd);g=n(g,"HEAP32",Ga);m=E(m);this._drawImageNine(d,
g,m,r,u||null)};a.Canvas.prototype.drawImageRect=function(d,g,m,r,u){a.Cd(this.Bd);E(g,P);E(m,ra);this._drawImageRect(d,P,ra,r,!!u)};a.Canvas.prototype.drawImageRectCubic=function(d,g,m,r,u,w){a.Cd(this.Bd);E(g,P);E(m,ra);this._drawImageRectCubic(d,P,ra,r,u,w||null)};a.Canvas.prototype.drawImageRectOptions=function(d,g,m,r,u,w){a.Cd(this.Bd);E(g,P);E(m,ra);this._drawImageRectOptions(d,P,ra,r,u,w||null)};a.Canvas.prototype.drawLine=function(d,g,m,r,u){a.Cd(this.Bd);this._drawLine(d,g,m,r,u)};a.Canvas.prototype.drawOval=
function(d,g){a.Cd(this.Bd);d=E(d);this._drawOval(d,g)};a.Canvas.prototype.drawPaint=function(d){a.Cd(this.Bd);this._drawPaint(d)};a.Canvas.prototype.drawParagraph=function(d,g,m){a.Cd(this.Bd);this._drawParagraph(d,g,m)};a.Canvas.prototype.drawPatch=function(d,g,m,r,u){if(24>d.length)throw"Need 12 cubic points";if(g&&4>g.length)throw"Need 4 colors";if(m&&8>m.length)throw"Need 4 shader coordinates";a.Cd(this.Bd);const w=n(d,"HEAPF32"),B=g?n(c(g),"HEAPU32"):0,J=m?n(m,"HEAPF32"):0;r||(r=a.BlendMode.Modulate);
this._drawPatch(w,B,J,r,u);h(J,m);h(B,g);h(w,d)};a.Canvas.prototype.drawPath=function(d,g){a.Cd(this.Bd);this._drawPath(d,g)};a.Canvas.prototype.drawPicture=function(d){a.Cd(this.Bd);this._drawPicture(d)};a.Canvas.prototype.drawPoints=function(d,g,m){a.Cd(this.Bd);var r=n(g,"HEAPF32");this._drawPoints(d,r,g.length/2,m);h(r,g)};a.Canvas.prototype.drawRRect=function(d,g){a.Cd(this.Bd);d=M(d);this._drawRRect(d,g)};a.Canvas.prototype.drawRect=function(d,g){a.Cd(this.Bd);d=E(d);this._drawRect(d,g)};a.Canvas.prototype.drawRect4f=
function(d,g,m,r,u){a.Cd(this.Bd);this._drawRect4f(d,g,m,r,u)};a.Canvas.prototype.drawShadow=function(d,g,m,r,u,w,B){a.Cd(this.Bd);var J=n(u,"HEAPF32"),F=n(w,"HEAPF32");g=n(g,"HEAPF32",pb);m=n(m,"HEAPF32",qb);this._drawShadow(d,g,m,r,J,F,B);h(J,u);h(F,w)};a.getShadowLocalBounds=function(d,g,m,r,u,w,B){d=p(d);m=n(m,"HEAPF32",pb);r=n(r,"HEAPF32",qb);if(!this._getShadowLocalBounds(d,g,m,r,u,w,P))return null;g=W.toTypedArray();return B?(B.set(g),B):g.slice()};a.Canvas.prototype.drawTextBlob=function(d,
g,m,r){a.Cd(this.Bd);this._drawTextBlob(d,g,m,r)};a.Canvas.prototype.drawVertices=function(d,g,m){a.Cd(this.Bd);this._drawVertices(d,g,m)};a.Canvas.prototype.getDeviceClipBounds=function(d){this._getDeviceClipBounds(Ga);var g=Va.toTypedArray();d?d.set(g):d=g.slice();return d};a.Canvas.prototype.quickReject=function(d){d=E(d);return this._quickReject(d)};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(ba);for(var d=ba,g=Array(16),m=0;16>m;m++)g[m]=a.HEAPF32[d/4+m];return g};a.Canvas.prototype.getTotalMatrix=
function(){this._getTotalMatrix(L);for(var d=Array(9),g=0;9>g;g++)d[g]=a.HEAPF32[L/4+g];return d};a.Canvas.prototype.makeSurface=function(d){d=this._makeSurface(d);d.Bd=this.Bd;return d};a.Canvas.prototype.readPixels=function(d,g,m,r,u){a.Cd(this.Bd);return l(this,d,g,m,r,u)};a.Canvas.prototype.saveLayer=function(d,g,m,r,u){g=E(g);return this._saveLayer(d||null,g,m||null,r||0,u||a.TileMode.Clamp)};a.Canvas.prototype.writePixels=function(d,g,m,r,u,w,B,J){if(d.byteLength%(g*m))throw"pixels length must be a multiple of the srcWidth * srcHeight";
a.Cd(this.Bd);var F=d.byteLength/(g*m);w=w||a.AlphaType.Unpremul;B=B||a.ColorType.RGBA_8888;J=J||a.ColorSpace.SRGB;var R=F*g;F=n(d,"HEAPU8");g=this._writePixels({width:g,height:m,colorType:B,alphaType:w,colorSpace:J},F,R,r,u);h(F,d);return g};a.ColorFilter.MakeBlend=function(d,g,m){d=v(d);m=m||a.ColorSpace.SRGB;return a.ColorFilter._MakeBlend(d,g,m)};a.ColorFilter.MakeMatrix=function(d){if(!d||20!==d.length)throw"invalid color matrix";var g=n(d,"HEAPF32"),m=a.ColorFilter._makeMatrix(g);h(g,d);return m};
a.ContourMeasure.prototype.getPosTan=function(d,g){this._getPosTan(d,P);d=W.toTypedArray();return g?(g.set(d),g):d.slice()};a.ImageFilter.prototype.getOutputBounds=function(d,g,m){d=E(d,P);g=p(g);this._getOutputBounds(d,g,Ga);g=Va.toTypedArray();return m?(m.set(g),m):g.slice()};a.ImageFilter.MakeDropShadow=function(d,g,m,r,u,w){u=v(u,X);return a.ImageFilter._MakeDropShadow(d,g,m,r,u,w)};a.ImageFilter.MakeDropShadowOnly=function(d,g,m,r,u,w){u=v(u,X);return a.ImageFilter._MakeDropShadowOnly(d,g,m,
r,u,w)};a.ImageFilter.MakeImage=function(d,g,m,r){m=E(m,P);r=E(r,ra);if("B"in g&&"C"in g)return a.ImageFilter._MakeImageCubic(d,g.B,g.C,m,r);const u=g.filter;let w=a.MipmapMode.None;"mipmap"in g&&(w=g.mipmap);return a.ImageFilter._MakeImageOptions(d,u,w,m,r)};a.ImageFilter.MakeMatrixTransform=function(d,g,m){d=p(d);if("B"in g&&"C"in g)return a.ImageFilter._MakeMatrixTransformCubic(d,g.B,g.C,m);const r=g.filter;let u=a.MipmapMode.None;"mipmap"in g&&(u=g.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(d,
r,u,m)};a.Paint.prototype.getColor=function(){this._getColor(X);return A(X)};a.Paint.prototype.setColor=function(d,g){g=g||null;d=v(d);this._setColor(d,g)};a.Paint.prototype.setColorComponents=function(d,g,m,r,u){u=u||null;d=z(d,g,m,r);this._setColor(d,u)};a.Path.prototype.getPoint=function(d,g){this._getPoint(d,P);d=W.toTypedArray();return g?(g[0]=d[0],g[1]=d[1],g):d.slice(0,2)};a.Picture.prototype.makeShader=function(d,g,m,r,u){r=p(r);u=E(u);return this._makeShader(d,g,m,r,u)};a.Picture.prototype.cullRect=
function(d){this._cullRect(P);var g=W.toTypedArray();return d?(d.set(g),d):g.slice()};a.PictureRecorder.prototype.beginRecording=function(d,g){d=E(d);return this._beginRecording(d,!!g)};a.Surface.prototype.getCanvas=function(){var d=this._getCanvas();d.Bd=this.Bd;return d};a.Surface.prototype.makeImageSnapshot=function(d){a.Cd(this.Bd);d=n(d,"HEAP32",Ga);return this._makeImageSnapshot(d)};a.Surface.prototype.makeSurface=function(d){a.Cd(this.Bd);d=this._makeSurface(d);d.Bd=this.Bd;return d};a.Surface.prototype.Be=
function(d,g){this.Wd||(this.Wd=this.getCanvas());return requestAnimationFrame(function(){a.Cd(this.Bd);d(this.Wd);this.flush(g)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.Be);a.Surface.prototype.ye=function(d,g){this.Wd||(this.Wd=this.getCanvas());requestAnimationFrame(function(){a.Cd(this.Bd);d(this.Wd);this.flush(g);this.dispose()}.bind(this))};a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=a.Surface.prototype.ye);
a.PathEffect.MakeDash=function(d,g){g||=0;if(!d.length||1===d.length%2)throw"Intervals array must have even length";var m=n(d,"HEAPF32");g=a.PathEffect._MakeDash(m,d.length,g);h(m,d);return g};a.PathEffect.MakeLine2D=function(d,g){g=p(g);return a.PathEffect._MakeLine2D(d,g)};a.PathEffect.MakePath2D=function(d,g){d=p(d);return a.PathEffect._MakePath2D(d,g)};a.Shader.MakeColor=function(d,g){g=g||null;d=v(d);return a.Shader._MakeColor(d,g)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;
a.Shader.MakeLinearGradient=function(d,g,m,r,u,w,B,J){J=J||null;var F=k(m),R=n(r,"HEAPF32");B=B||0;w=p(w);var T=W.toTypedArray();T.set(d);T.set(g,2);d=a.Shader._MakeLinearGradient(P,F.Md,F.colorType,R,F.count,u,B,w,J);h(F.Md,m);r&&h(R,r);return d};a.Shader.MakeRadialGradient=function(d,g,m,r,u,w,B,J){J=J||null;var F=k(m),R=n(r,"HEAPF32");B=B||0;w=p(w);d=a.Shader._MakeRadialGradient(d[0],d[1],g,F.Md,F.colorType,R,F.count,u,B,w,J);h(F.Md,m);r&&h(R,r);return d};a.Shader.MakeSweepGradient=function(d,
g,m,r,u,w,B,J,F,R){R=R||null;var T=k(m),sa=n(r,"HEAPF32");B=B||0;J=J||0;F=F||360;w=p(w);d=a.Shader._MakeSweepGradient(d,g,T.Md,T.colorType,sa,T.count,u,J,F,B,w,R);h(T.Md,m);r&&h(sa,r);return d};a.Shader.MakeTwoPointConicalGradient=function(d,g,m,r,u,w,B,J,F,R){R=R||null;var T=k(u),sa=n(w,"HEAPF32");F=F||0;J=p(J);var Ha=W.toTypedArray();Ha.set(d);Ha.set(m,2);d=a.Shader._MakeTwoPointConicalGradient(P,g,r,T.Md,T.colorType,sa,T.count,B,F,J,R);h(T.Md,u);w&&h(sa,w);return d};a.Vertices.prototype.bounds=
function(d){this._bounds(P);var g=W.toTypedArray();return d?(d.set(g),d):g.slice()};a.Fd&&a.Fd.forEach(function(d){d()})};a.computeTonalColors=function(l){var d=n(l.ambient,"HEAPF32"),g=n(l.spot,"HEAPF32");this._computeTonalColors(d,g);var m={ambient:A(d),spot:A(g)};h(d,l.ambient);h(g,l.spot);return m};a.LTRBRect=function(l,d,g,m){return Float32Array.of(l,d,g,m)};a.XYWHRect=function(l,d,g,m){return Float32Array.of(l,d,l+g,d+m)};a.LTRBiRect=function(l,d,g,m){return Int32Array.of(l,d,g,m)};a.XYWHiRect=
function(l,d,g,m){return Int32Array.of(l,d,l+g,d+m)};a.RRectXY=function(l,d,g){return Float32Array.of(l[0],l[1],l[2],l[3],d,g,d,g,d,g,d,g)};a.MakeAnimatedImageFromEncoded=function(l){l=new Uint8Array(l);var d=a._malloc(l.byteLength);a.HEAPU8.set(l,d);return(l=a._decodeAnimatedImage(d,l.byteLength))?l:null};a.MakeImageFromEncoded=function(l){l=new Uint8Array(l);var d=a._malloc(l.byteLength);a.HEAPU8.set(l,d);return(l=a._decodeImage(d,l.byteLength))?l:null};var Wa=null;a.MakeImageFromCanvasImageSource=
function(l){var d=l.width,g=l.height;Wa||=document.createElement("canvas");Wa.width=d;Wa.height=g;var m=Wa.getContext("2d",{willReadFrequently:!0});m.drawImage(l,0,0);l=m.getImageData(0,0,d,g);return a.MakeImage({width:d,height:g,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},l.data,4*d)};a.MakeImage=function(l,d,g){var m=a._malloc(d.length);a.HEAPU8.set(d,m);return a._MakeImage(l,m,d.length,g)};a.MakeVertices=function(l,d,g,m,r,u){var w=r&&r.length||
0,B=0;g&&g.length&&(B|=1);m&&m.length&&(B|=2);void 0===u||u||(B|=4);l=new a._VerticesBuilder(l,d.length/2,w,B);n(d,"HEAPF32",l.positions());l.texCoords()&&n(g,"HEAPF32",l.texCoords());l.colors()&&n(c(m),"HEAPU32",l.colors());l.indices()&&n(r,"HEAPU16",l.indices());return l.detach()};(function(l){l.Fd=l.Fd||[];l.Fd.push(function(){l.Bidi.getBidiRegions=function(d,g){if((d=l.Bidi._getBidiRegions(d,g===l.TextDirection.LTR?1:0))&&d.length){g=[];for(let m=0;m<d.length;m+=3)g.push({start:d[m],end:d[m+1],
level:d[m+2]});d=g}else d=[];return d};l.Bidi.reorderVisual=function(d){var g=n(d,"HEAPU8"),m=l.Bidi._reorderVisual(g,d&&d.length||0);h(g,d);if(m&&m.length){d=[];for(g=0;g<m.length;g+=1)d.push({index:m[g]});m=d}else m=[];return m};l.CodeUnits.compute=function(d){if((d=l.CodeUnits._compute(d))&&d.length){var g=[];for(let m=0;m<d.length;m+=1)g.push({flags:d[m]});d=g}else d=[];return d};l.TextDirection||(l.TextDirection={LTR:{value:1},RTL:{value:0}})})})(q);a.Fd=a.Fd||[];a.Fd.push(function(){});a.Fd=
a.Fd||[];a.Fd.push(function(){a.MakePicture=function(l){l=new Uint8Array(l);var d=a._malloc(l.byteLength);a.HEAPU8.set(l,d);return(l=a._MakePicture(d,l.byteLength))?l:null}});a.Fd=a.Fd||[];a.Fd.push(function(){a.RuntimeEffect.Make=function(l,d){return a.RuntimeEffect._Make(l,{onError:d||function(g){console.log("RuntimeEffect error",g)}})};a.RuntimeEffect.MakeForBlender=function(l,d){return a.RuntimeEffect._MakeForBlender(l,{onError:d||function(g){console.log("RuntimeEffect error",g)}})};a.RuntimeEffect.prototype.makeShader=
function(l,d){var g=!l._ck,m=n(l,"HEAPF32");d=p(d);return this._makeShader(m,4*l.length,g,d)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(l,d,g){var m=!l._ck,r=n(l,"HEAPF32");g=p(g);for(var u=[],w=0;w<d.length;w++)u.push(d[w].Ad.Dd);d=n(u,"HEAPU32");return this._makeShaderWithChildren(r,4*l.length,m,d,u.length,g)};a.RuntimeEffect.prototype.makeBlender=function(l){var d=!l._ck,g=n(l,"HEAPF32");return this._makeBlender(g,4*l.length,d)}})})(q);var ma=Object.assign({},q),na="",oa,pa;
if(ea||fa)fa?na=self.location.href:"undefined"!=typeof document&&document.currentScript&&(na=document.currentScript.src),_scriptName&&(na=_scriptName),na.startsWith("blob:")?na="":na=na.substr(0,na.replace(/[?#].*/,"").lastIndexOf("/")+1),fa&&(pa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),oa=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));
var qa=console.log.bind(console),ta=console.error.bind(console);Object.assign(q,ma);ma=null;var ua,va=!1,wa,y,xa,za,C,D,G,Aa;function Ba(){var a=ua.buffer;q.HEAP8=wa=new Int8Array(a);q.HEAP16=xa=new Int16Array(a);q.HEAPU8=y=new Uint8Array(a);q.HEAPU16=za=new Uint16Array(a);q.HEAP32=C=new Int32Array(a);q.HEAPU32=D=new Uint32Array(a);q.HEAPF32=G=new Float32Array(a);q.HEAPF64=Aa=new Float64Array(a)}var Ca=[],Da=[],Ea=[],Fa=0,Ia=null,Ja=null;
function Ka(a){a="Aborted("+a+")";ta(a);va=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}var La=a=>a.startsWith("data:application/octet-stream;base64,"),Ma;function Na(a){return oa(a).then(b=>new Uint8Array(b),()=>{if(pa)var b=pa(a);else throw"both async and sync fetching of the wasm failed";return b})}function Oa(a,b,c){return Na(a).then(e=>WebAssembly.instantiate(e,b)).then(c,e=>{ta(`failed to asynchronously prepare wasm: ${e}`);Ka(e)})}
function Pa(a,b){var c=Ma;return"function"!=typeof WebAssembly.instantiateStreaming||La(c)||"function"!=typeof fetch?Oa(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){ta(`wasm streaming compile failed: ${f}`);ta("falling back to ArrayBuffer instantiation");return Oa(c,a,b)}))}var Qa=a=>{a.forEach(b=>b(q))};class Ra{constructor(a){this.Dd=a-24}}var Sa=0,Ta=0,Ua={},Xa=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function Ya(a){return this.fromWireType(D[a>>2])}var Za={},$a={},ab={},bb,db=(a,b,c)=>{function e(k){k=c(k);if(k.length!==a.length)throw new bb("Mismatched type converter count");for(var p=0;p<a.length;++p)cb(a[p],k[p])}a.forEach(k=>ab[k]=b);var f=Array(b.length),h=[],n=0;b.forEach((k,p)=>{$a.hasOwnProperty(k)?f[p]=$a[k]:(h.push(k),Za.hasOwnProperty(k)||(Za[k]=[]),Za[k].push(()=>{f[p]=$a[k];++n;n===h.length&&e(f)}))});0===h.length&&e(f)},eb,H=a=>{for(var b="";y[a];)b+=eb[y[a++]];return b},I;
function fb(a,b,c={}){var e=b.name;if(!a)throw new I(`type "${e}" must have a positive integer typeid pointer`);if($a.hasOwnProperty(a)){if(c.Ne)return;throw new I(`Cannot register type '${e}' twice`);}$a[a]=b;delete ab[a];Za.hasOwnProperty(a)&&(b=Za[a],delete Za[a],b.forEach(f=>f()))}function cb(a,b,c={}){return fb(a,b,c)}
var gb=a=>{throw new I(a.Ad.Gd.Ed.name+" instance already deleted");},hb=!1,ib=()=>{},jb=(a,b,c)=>{if(b===c)return a;if(void 0===c.Jd)return null;a=jb(a,b,c.Jd);return null===a?null:c.Fe(a)},kb={},lb={},mb=(a,b)=>{if(void 0===b)throw new I("ptr should not be undefined");for(;a.Jd;)b=a.ae(b),a=a.Jd;return lb[b]},rb=(a,b)=>{if(!b.Gd||!b.Dd)throw new bb("makeClassHandle requires ptr and ptrType");if(!!b.Kd!==!!b.Hd)throw new bb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return nb(Object.create(a,
{Ad:{value:b,writable:!0}}))},nb=a=>{if("undefined"===typeof FinalizationRegistry)return nb=b=>b,a;hb=new FinalizationRegistry(b=>{b=b.Ad;--b.count.value;0===b.count.value&&(b.Hd?b.Kd.Qd(b.Hd):b.Gd.Ed.Qd(b.Dd))});nb=b=>{var c=b.Ad;c.Hd&&hb.register(b,{Ad:c},b);return b};ib=b=>{hb.unregister(b)};return nb(a)},sb=[];function tb(){}
var ub=(a,b)=>Object.defineProperty(b,"name",{value:a}),vb=(a,b,c)=>{if(void 0===a[b].Id){var e=a[b];a[b]=function(...f){if(!a[b].Id.hasOwnProperty(f.length))throw new I(`Function '${c}' called with an invalid number of arguments (${f.length}) - expects one of (${a[b].Id})!`);return a[b].Id[f.length].apply(this,f)};a[b].Id=[];a[b].Id[e.Rd]=e}},wb=(a,b,c)=>{if(q.hasOwnProperty(a)){if(void 0===c||void 0!==q[a].Id&&void 0!==q[a].Id[c])throw new I(`Cannot register public name '${a}' twice`);vb(q,a,a);
if(q[a].Id.hasOwnProperty(c))throw new I(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);q[a].Id[c]=b}else q[a]=b,q[a].Rd=c},xb=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function yb(a,b,c,e,f,h,n,k){this.name=a;this.constructor=b;this.Vd=c;this.Qd=e;this.Jd=f;this.Ie=h;this.ae=n;this.Fe=k;this.Qe=[]}
var zb=(a,b,c)=>{for(;b!==c;){if(!b.ae)throw new I(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ae(a);b=b.Jd}return a};function Ab(a,b){if(null===b){if(this.me)throw new I(`null is not a valid ${this.name}`);return 0}if(!b.Ad)throw new I(`Cannot pass "${Bb(b)}" as a ${this.name}`);if(!b.Ad.Dd)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);return zb(b.Ad.Dd,b.Ad.Gd.Ed,this.Ed)}
function Cb(a,b){if(null===b){if(this.me)throw new I(`null is not a valid ${this.name}`);if(this.fe){var c=this.ne();null!==a&&a.push(this.Qd,c);return c}return 0}if(!b||!b.Ad)throw new I(`Cannot pass "${Bb(b)}" as a ${this.name}`);if(!b.Ad.Dd)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ee&&b.Ad.Gd.ee)throw new I(`Cannot convert argument of type ${b.Ad.Kd?b.Ad.Kd.name:b.Ad.Gd.name} to parameter type ${this.name}`);c=zb(b.Ad.Dd,b.Ad.Gd.Ed,this.Ed);if(this.fe){if(void 0===
b.Ad.Hd)throw new I("Passing raw pointer to smart pointer is illegal");switch(this.Ve){case 0:if(b.Ad.Kd===this)c=b.Ad.Hd;else throw new I(`Cannot convert argument of type ${b.Ad.Kd?b.Ad.Kd.name:b.Ad.Gd.name} to parameter type ${this.name}`);break;case 1:c=b.Ad.Hd;break;case 2:if(b.Ad.Kd===this)c=b.Ad.Hd;else{var e=b.clone();c=this.Re(c,Db(()=>e["delete"]()));null!==a&&a.push(this.Qd,c)}break;default:throw new I("Unsupporting sharing policy");}}return c}
function Eb(a,b){if(null===b){if(this.me)throw new I(`null is not a valid ${this.name}`);return 0}if(!b.Ad)throw new I(`Cannot pass "${Bb(b)}" as a ${this.name}`);if(!b.Ad.Dd)throw new I(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.Ad.Gd.ee)throw new I(`Cannot convert argument of type ${b.Ad.Gd.name} to parameter type ${this.name}`);return zb(b.Ad.Dd,b.Ad.Gd.Ed,this.Ed)}
function Fb(a,b,c,e,f,h,n,k,p,t,v){this.name=a;this.Ed=b;this.me=c;this.ee=e;this.fe=f;this.Pe=h;this.Ve=n;this.ue=k;this.ne=p;this.Re=t;this.Qd=v;f||void 0!==b.Jd?this.toWireType=Cb:(this.toWireType=e?Ab:Eb,this.Nd=null)}
var Gb=(a,b,c)=>{if(!q.hasOwnProperty(a))throw new bb("Replacing nonexistent public symbol");void 0!==q[a].Id&&void 0!==c?q[a].Id[c]=b:(q[a]=b,q[a].Rd=c)},Hb,Ib=(a,b,c=[])=>{a.includes("j")?(a=a.replace(/p/g,"i"),b=(0,q["dynCall_"+a])(b,...c)):b=Hb.get(b)(...c);return b},Jb=(a,b)=>(...c)=>Ib(a,b,c),K=(a,b)=>{a=H(a);var c=a.includes("j")?Jb(a,b):Hb.get(b);if("function"!=typeof c)throw new I(`unknown function pointer with signature ${a}: ${b}`);return c},Kb,Tb=a=>{a=Lb(a);var b=H(a);Sb(a);return b},
Ub=(a,b)=>{function c(h){f[h]||$a[h]||(ab[h]?ab[h].forEach(c):(e.push(h),f[h]=!0))}var e=[],f={};b.forEach(c);throw new Kb(`${a}: `+e.map(Tb).join([", "]));};function Vb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].Nd)return!0;return!1}
function Wb(a,b,c,e,f){var h=b.length;if(2>h)throw new I("argTypes array size mismatch! Must at least get return value and 'this' types!");var n=null!==b[1]&&null!==c,k=Vb(b),p="void"!==b[0].name,t=h-2,v=Array(t),z=[],A=[];return ub(a,function(...E){A.length=0;z.length=n?2:1;z[0]=f;if(n){var M=b[1].toWireType(A,this);z[1]=M}for(var L=0;L<t;++L)v[L]=b[L+2].toWireType(A,E[L]),z.push(v[L]);E=e(...z);if(k)Xa(A);else for(L=n?1:2;L<b.length;L++){var V=1===L?M:v[L-2];null!==b[L].Nd&&b[L].Nd(V)}M=p?b[0].fromWireType(E):
void 0;return M})}
var Xb=(a,b)=>{for(var c=[],e=0;e<a;e++)c.push(D[b+4*e>>2]);return c},Yb=a=>{a=a.trim();const b=a.indexOf("(");return-1!==b?a.substr(0,b):a},Zb=[],$b=[],ac=a=>{9<a&&0===--$b[a+1]&&($b[a]=void 0,Zb.push(a))},bc=a=>{if(!a)throw new I("Cannot use deleted val. handle = "+a);return $b[a]},Db=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Zb.pop()||$b.length;$b[b]=a;$b[b+1]=1;return b}},cc={name:"emscripten::val",fromWireType:a=>{var b=bc(a);ac(a);
return b},toWireType:(a,b)=>Db(b),Ld:8,readValueFromPointer:Ya,Nd:null},dc=(a,b,c)=>{switch(b){case 1:return c?function(e){return this.fromWireType(wa[e])}:function(e){return this.fromWireType(y[e])};case 2:return c?function(e){return this.fromWireType(xa[e>>1])}:function(e){return this.fromWireType(za[e>>1])};case 4:return c?function(e){return this.fromWireType(C[e>>2])}:function(e){return this.fromWireType(D[e>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ec=(a,b)=>
{var c=$a[a];if(void 0===c)throw a=`${b} has unknown type ${Tb(a)}`,new I(a);return c},Bb=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a},fc=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(G[c>>2])};case 8:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},gc=(a,b,c)=>{switch(b){case 1:return c?e=>wa[e]:e=>y[e];case 2:return c?e=>xa[e>>1]:e=>za[e>>
1];case 4:return c?e=>C[e>>2]:e=>D[e>>2];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},hc=(a,b,c)=>{var e=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var n=a.charCodeAt(h);if(55296<=n&&57343>=n){var k=a.charCodeAt(++h);n=65536+((n&1023)<<10)|k&1023}if(127>=n){if(b>=c)break;e[b++]=n}else{if(2047>=n){if(b+1>=c)break;e[b++]=192|n>>6}else{if(65535>=n){if(b+2>=c)break;e[b++]=224|n>>12}else{if(b+3>=c)break;e[b++]=240|n>>18;e[b++]=128|n>>12&63}e[b++]=128|n>>6&
63}e[b++]=128|n&63}}e[b]=0;return b-f},ic=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},jc="undefined"!=typeof TextDecoder?new TextDecoder:void 0,kc=(a,b=0,c=NaN)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&jc)return jc.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|h);else{var n=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|n:
(f&7)<<18|h<<12|n<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},lc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,mc=(a,b)=>{var c=a>>1;for(var e=c+b/2;!(c>=e)&&za[c];)++c;c<<=1;if(32<c-a&&lc)return lc.decode(y.subarray(a,c));c="";for(e=0;!(e>=b/2);++e){var f=xa[a+2*e>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},nc=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var e=
b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)xa[b>>1]=a.charCodeAt(f),b+=2;xa[b>>1]=0;return b-e},oc=a=>2*a.length,pc=(a,b)=>{for(var c=0,e="";!(c>=b/4);){var f=C[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e},qc=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var n=a.charCodeAt(++f);h=65536+((h&1023)<<10)|n&1023}C[b>>2]=h;b+=
4;if(b+4>c)break}C[b>>2]=0;return b-e},rc=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b},sc=(a,b,c)=>{var e=[];a=a.toWireType(e,c);e.length&&(D[b>>2]=Db(e));return a},tc=[],uc={},vc=a=>{var b=uc[a];return void 0===b?H(a):b},wc=()=>{function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;
"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");},xc=a=>{var b=tc.length;tc.push(a);return b},yc=(a,b)=>{for(var c=Array(a),e=0;e<a;++e)c[e]=ec(D[b+4*e>>2],"parameter "+e);return c},zc=Reflect.construct,N,Ac=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,e)=>b.vertexAttribDivisorANGLE(c,
e),a.drawArraysInstanced=(c,e,f,h)=>b.drawArraysInstancedANGLE(c,e,f,h),a.drawElementsInstanced=(c,e,f,h,n)=>b.drawElementsInstancedANGLE(c,e,f,h,n))},Bc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Cc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,e)=>b.drawBuffersWEBGL(c,e))},Dc=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Ec=1,Fc=[],Gc=[],Hc=[],Ic=[],ia=[],Jc=[],Kc=[],la=[],O=[],Lc=[],Mc=[],Nc={},Pc={},Qc=4,Rc=0,ha=a=>{for(var b=Ec++,c=a.length;c<b;c++)a[c]=null;return b},Sc=(a,b,c,e)=>{for(var f=0;f<a;f++){var h=N[c](),n=h&&ha(e);h?(h.name=n,e[n]=h):Q||=1282;C[b+4*f>>2]=n}},ja=(a,b)=>{a.pe||(a.pe=a.getContext,a.getContext=function(e,f){f=a.pe(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=1<b.majorVersion?a.getContext("webgl2",
b):a.getContext("webgl",b);return c?Tc(c,b):0},Tc=(a,b)=>{var c=ha(la),e={handle:c,attributes:b,version:b.majorVersion,Od:a};a.canvas&&(a.canvas.xe=e);la[c]=e;("undefined"==typeof b.Ge||b.Ge)&&Uc(e);return c},ka=a=>{x=la[a];q.We=N=x?.Od;return!(a&&!N)},Uc=a=>{a||=x;if(!a.Oe){a.Oe=!0;var b=a.Od;b.$e=b.getExtension("WEBGL_multi_draw");b.Ye=b.getExtension("EXT_polygon_offset_clamp");b.Xe=b.getExtension("EXT_clip_control");b.bf=b.getExtension("WEBGL_polygon_mode");Ac(b);Bc(b);Cc(b);b.re=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");
b.te=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Pd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Pd)b.Pd=b.getExtension("EXT_disjoint_timer_query");Dc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},x,Q,Vc=(a,b)=>{N.bindFramebuffer(a,Hc[b])},Wc=a=>{N.bindVertexArray(Kc[a])},Xc=a=>N.clear(a),Yc=(a,b,c,e)=>N.clearColor(a,b,c,e),Zc=a=>N.clearStencil(a),$c=(a,b)=>{for(var c=0;c<a;c++){var e=C[b+
4*c>>2];N.deleteVertexArray(Kc[e]);Kc[e]=null}},ad=[],bd=(a,b)=>{Sc(a,b,"createVertexArray",Kc)};function cd(){var a=Dc(N);return a=a.concat(a.map(b=>"GL_"+b))}
var dd=(a,b,c)=>{if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=c&&1!=c&&(Q||=1280);return;case 34814:case 36345:e=0;break;case 34466:var f=N.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>x.version){Q||=1282;return}e=cd().length;break;case 33307:case 33308:if(2>x.version){Q||=1280;return}e=33307==a?3:0}if(void 0===e)switch(f=N.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":Q||=1280;return;case "object":if(null===f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=
0;break;default:Q||=1280;return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:C[b+4*a>>2]=f[a];break;case 2:G[b+4*a>>2]=f[a];break;case 4:wa[b+a]=f[a]?1:0}return}try{e=f.name|0}catch(h){Q||=1280;ta(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${h})`);return}}break;default:Q||=1280;ta(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${f} of type ${typeof f}!`);
return}switch(c){case 1:c=e;D[b>>2]=c;D[b+4>>2]=(c-D[b>>2])/4294967296;break;case 0:C[b>>2]=e;break;case 2:G[b>>2]=e;break;case 4:wa[b]=e?1:0}}else Q||=1281},ed=(a,b)=>dd(a,b,0),fd=(a,b,c)=>{if(c){a=O[a];b=2>x.version?N.Pd.getQueryObjectEXT(a,b):N.getQueryParameter(a,b);var e;"boolean"==typeof b?e=b?1:0:e=b;D[c>>2]=e;D[c+4>>2]=(e-D[c>>2])/4294967296}else Q||=1281},hd=a=>{var b=ic(a)+1,c=gd(b);c&&hc(a,c,b);return c},jd=a=>{var b=Nc[a];if(!b){switch(a){case 7939:b=hd(cd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
N.getParameter(a))||(Q||=1280);b=b?hd(b):0;break;case 7938:b=N.getParameter(7938);var c=`OpenGL ES 2.0 (${b})`;2<=x.version&&(c=`OpenGL ES 3.0 (${b})`);b=hd(c);break;case 35724:b=N.getParameter(35724);c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=hd(b);break;default:Q||=1280}Nc[a]=b}return b},kd=(a,b)=>{if(2>x.version)return Q||=1282,0;var c=Pc[a];if(c)return 0>b||b>=c.length?(Q||=1281,0):c[b];switch(a){case 7939:return c=
cd().map(hd),c=Pc[a]=c,0>b||b>=c.length?(Q||=1281,0):c[b];default:return Q||=1280,0}},ld=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),md=a=>{a-=5120;return 0==a?wa:1==a?y:2==a?xa:4==a?C:6==a?G:5==a||28922==a||28520==a||30779==a||30782==a?D:za},nd=(a,b,c,e,f)=>{a=md(a);b=e*((Rc||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Qc-1&-Qc);return a.subarray(f>>>31-Math.clz32(a.BYTES_PER_ELEMENT),f+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},U=a=>{var b=N.Ee;if(b){var c=
b.$d[a];"number"==typeof c&&(b.$d[a]=c=N.getUniformLocation(b,b.ve[a]+(0<c?`[${c}]`:"")));return c}Q||=1282},od=[],pd=[],qd={},sd=()=>{if(!rd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:"./this.program"},b;for(b in qd)void 0===qd[b]?delete a[b]:a[b]=qd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);rd=c}return rd},rd,td=[null,[],[]];
bb=q.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var ud=Array(256),vd=0;256>vd;++vd)ud[vd]=String.fromCharCode(vd);eb=ud;I=q.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Object.assign(tb.prototype,{isAliasOf:function(a){if(!(this instanceof tb&&a instanceof tb))return!1;var b=this.Ad.Gd.Ed,c=this.Ad.Dd;a.Ad=a.Ad;var e=a.Ad.Gd.Ed;for(a=a.Ad.Dd;b.Jd;)c=b.ae(c),b=b.Jd;for(;e.Jd;)a=e.ae(a),e=e.Jd;return b===e&&c===a},clone:function(){this.Ad.Dd||gb(this);if(this.Ad.Zd)return this.Ad.count.value+=1,this;var a=nb,b=Object,c=b.create,e=Object.getPrototypeOf(this),f=this.Ad;a=a(c.call(b,e,{Ad:{value:{count:f.count,Yd:f.Yd,Zd:f.Zd,Dd:f.Dd,Gd:f.Gd,Hd:f.Hd,Kd:f.Kd}}}));a.Ad.count.value+=
1;a.Ad.Yd=!1;return a},["delete"](){this.Ad.Dd||gb(this);if(this.Ad.Yd&&!this.Ad.Zd)throw new I("Object already scheduled for deletion");ib(this);var a=this.Ad;--a.count.value;0===a.count.value&&(a.Hd?a.Kd.Qd(a.Hd):a.Gd.Ed.Qd(a.Dd));this.Ad.Zd||(this.Ad.Hd=void 0,this.Ad.Dd=void 0)},isDeleted:function(){return!this.Ad.Dd},deleteLater:function(){this.Ad.Dd||gb(this);if(this.Ad.Yd&&!this.Ad.Zd)throw new I("Object already scheduled for deletion");sb.push(this);this.Ad.Yd=!0;return this}});
Object.assign(Fb.prototype,{Je(a){this.ue&&(a=this.ue(a));return a},qe(a){this.Qd?.(a)},Ld:8,readValueFromPointer:Ya,fromWireType:function(a){function b(){return this.fe?rb(this.Ed.Vd,{Gd:this.Pe,Dd:c,Kd:this,Hd:a}):rb(this.Ed.Vd,{Gd:this,Dd:a})}var c=this.Je(a);if(!c)return this.qe(a),null;var e=mb(this.Ed,c);if(void 0!==e){if(0===e.Ad.count.value)return e.Ad.Dd=c,e.Ad.Hd=a,e.clone();e=e.clone();this.qe(a);return e}e=this.Ed.Ie(c);e=kb[e];if(!e)return b.call(this);e=this.ee?e.De:e.pointerType;var f=
jb(c,this.Ed,e.Ed);return null===f?b.call(this):this.fe?rb(e.Ed.Vd,{Gd:e,Dd:f,Kd:this,Hd:a}):rb(e.Ed.Vd,{Gd:e,Dd:f})}});Kb=q.UnboundTypeError=((a,b)=>{var c=ub(b,function(e){this.name=b;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError");
$b.push(0,1,void 0,1,null,1,!0,1,!1,1);q.count_emval_handles=()=>$b.length/2-5-Zb.length;for(var Y=0;32>Y;++Y)ad.push(Array(Y));var wd=new Float32Array(288);for(Y=0;288>=Y;++Y)od[Y]=wd.subarray(0,Y);var xd=new Int32Array(288);for(Y=0;288>=Y;++Y)pd[Y]=xd.subarray(0,Y);
var Hd={w:(a,b,c)=>{var e=new Ra(a);D[e.Dd+16>>2]=0;D[e.Dd+4>>2]=b;D[e.Dd+8>>2]=c;Sa=a;Ta++;throw Sa;},$c:()=>{Ka("")},B:a=>{var b=Ua[a];delete Ua[a];var c=b.ne,e=b.Qd,f=b.se,h=f.map(n=>n.Me).concat(f.map(n=>n.Te));db([a],h,n=>{var k={};f.forEach((p,t)=>{var v=n[t],z=p.Ke,A=p.Le,E=n[t+f.length],M=p.Se,L=p.Ue;k[p.He]={read:V=>v.fromWireType(z(A,V)),write:(V,ba)=>{var S=[];M(L,V,E.toWireType(S,ba));Xa(S)}}});return[{name:b.name,fromWireType:p=>{var t={},v;for(v in k)t[v]=k[v].read(p);e(p);return t},
toWireType:(p,t)=>{for(var v in k)if(!(v in t))throw new TypeError(`Missing field: "${v}"`);var z=c();for(v in k)k[v].write(z,t[v]);null!==p&&p.push(e,z);return z},Ld:8,readValueFromPointer:Ya,Nd:e}]})},L:()=>{},_c:(a,b,c,e)=>{b=H(b);cb(a,{name:b,fromWireType:function(f){return!!f},toWireType:function(f,h){return h?c:e},Ld:8,readValueFromPointer:function(f){return this.fromWireType(y[f])},Nd:null})},d:(a,b,c,e,f,h,n,k,p,t,v,z,A)=>{v=H(v);h=K(f,h);k&&=K(n,k);t&&=K(p,t);A=K(z,A);var E=xb(v);wb(E,function(){Ub(`Cannot construct ${v} due to unbound types`,
[e])});db([a,b,c],e?[e]:[],M=>{M=M[0];if(e){var L=M.Ed;var V=L.Vd}else V=tb.prototype;M=ub(v,function(...ya){if(Object.getPrototypeOf(this)!==ba)throw new I("Use 'new' to construct "+v);if(void 0===S.Sd)throw new I(v+" has no accessible constructor");var W=S.Sd[ya.length];if(void 0===W)throw new I(`Tried to invoke ctor of ${v} with invalid number of parameters (${ya.length}) - expected (${Object.keys(S.Sd).toString()}) parameters instead!`);return W.apply(this,ya)});var ba=Object.create(V,{constructor:{value:M}});
M.prototype=ba;var S=new yb(v,M,ba,A,L,h,k,t);if(S.Jd){var X;(X=S.Jd).be??(X.be=[]);S.Jd.be.push(S)}L=new Fb(v,S,!0,!1,!1);X=new Fb(v+"*",S,!1,!1,!1);V=new Fb(v+" const*",S,!1,!0,!1);kb[a]={pointerType:X,De:V};Gb(E,M);return[L,X,V]})},c:(a,b,c,e,f,h,n)=>{var k=Xb(c,e);b=H(b);b=Yb(b);h=K(f,h);db([],[a],p=>{function t(){Ub(`Cannot call ${v} due to unbound types`,k)}p=p[0];var v=`${p.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var z=p.Ed.constructor;void 0===z[b]?(t.Rd=c-1,z[b]=t):(vb(z,
b,v),z[b].Id[c-1]=t);db([],k,A=>{A=[A[0],null].concat(A.slice(1));A=Wb(v,A,null,h,n);void 0===z[b].Id?(A.Rd=c-1,z[b]=A):z[b].Id[c-1]=A;if(p.Ed.be)for(const E of p.Ed.be)E.constructor.hasOwnProperty(b)||(E.constructor[b]=A);return[]});return[]})},s:(a,b,c,e,f,h)=>{var n=Xb(b,c);f=K(e,f);db([],[a],k=>{k=k[0];var p=`constructor ${k.name}`;void 0===k.Ed.Sd&&(k.Ed.Sd=[]);if(void 0!==k.Ed.Sd[b-1])throw new I(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
k.Ed.Sd[b-1]=()=>{Ub(`Cannot construct ${k.name} due to unbound types`,n)};db([],n,t=>{t.splice(1,0,null);k.Ed.Sd[b-1]=Wb(p,t,null,f,h);return[]});return[]})},a:(a,b,c,e,f,h,n,k)=>{var p=Xb(c,e);b=H(b);b=Yb(b);h=K(f,h);db([],[a],t=>{function v(){Ub(`Cannot call ${z} due to unbound types`,p)}t=t[0];var z=`${t.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&t.Ed.Qe.push(b);var A=t.Ed.Vd,E=A[b];void 0===E||void 0===E.Id&&E.className!==t.name&&E.Rd===c-2?(v.Rd=c-2,v.className=t.name,A[b]=
v):(vb(A,b,z),A[b].Id[c-2]=v);db([],p,M=>{M=Wb(z,M,t,h,n);void 0===A[b].Id?(M.Rd=c-2,A[b]=M):A[b].Id[c-2]=M;return[]});return[]})},n:(a,b,c)=>{a=H(a);db([],[b],e=>{e=e[0];q[a]=e.fromWireType(c);return[]})},Zc:a=>cb(a,cc),f:(a,b,c,e)=>{function f(){}b=H(b);f.values={};cb(a,{name:b,constructor:f,fromWireType:function(h){return this.constructor.values[h]},toWireType:(h,n)=>n.value,Ld:8,readValueFromPointer:dc(b,c,e),Nd:null});wb(b,f)},b:(a,b,c)=>{var e=ec(a,"enum");b=H(b);a=e.constructor;e=Object.create(e.constructor.prototype,
{value:{value:c},constructor:{value:ub(`${e.name}_${b}`,function(){})}});a.values[c]=e;a[b]=e},J:(a,b,c)=>{b=H(b);cb(a,{name:b,fromWireType:e=>e,toWireType:(e,f)=>f,Ld:8,readValueFromPointer:fc(b,c),Nd:null})},l:(a,b,c,e,f,h)=>{var n=Xb(b,c);a=H(a);a=Yb(a);f=K(e,f);wb(a,function(){Ub(`Cannot call ${a} due to unbound types`,n)},b-1);db([],n,k=>{k=[k[0],null].concat(k.slice(1));Gb(a,Wb(a,k,null,f,h),b-1);return[]})},r:(a,b,c,e,f)=>{b=H(b);-1===f&&(f=4294967295);f=k=>k;if(0===e){var h=32-8*c;f=k=>k<<
h>>>h}var n=b.includes("unsigned")?function(k,p){return p>>>0}:function(k,p){return p};cb(a,{name:b,fromWireType:f,toWireType:n,Ld:8,readValueFromPointer:gc(b,c,0!==e),Nd:null})},g:(a,b,c)=>{function e(h){return new f(wa.buffer,D[h+4>>2],D[h>>2])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=H(c);cb(a,{name:c,fromWireType:e,Ld:8,readValueFromPointer:e},{Ne:!0})},j:(a,b,c,e,f,h,n,k,p,t,v,z)=>{c=H(c);h=K(f,h);k=K(n,k);t=K(p,t);z=K(v,z);db([a],
[b],A=>{A=A[0];return[new Fb(c,A.Ed,!1,!1,!0,A,e,h,k,t,z)]})},I:(a,b)=>{b=H(b);var c="std::string"===b;cb(a,{name:b,fromWireType:function(e){var f=D[e>>2],h=e+4;if(c)for(var n=h,k=0;k<=f;++k){var p=h+k;if(k==f||0==y[p]){n=n?kc(y,n,p-n):"";if(void 0===t)var t=n;else t+=String.fromCharCode(0),t+=n;n=p+1}}else{t=Array(f);for(k=0;k<f;++k)t[k]=String.fromCharCode(y[h+k]);t=t.join("")}Sb(e);return t},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var h="string"==typeof f;if(!(h||
f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array))throw new I("Cannot pass non-string to std::string");var n=c&&h?ic(f):f.length;var k=gd(4+n+1),p=k+4;D[k>>2]=n;if(c&&h)hc(f,p,n+1);else if(h)for(h=0;h<n;++h){var t=f.charCodeAt(h);if(255<t)throw Sb(p),new I("String has UTF-16 code units that do not fit in 8 bits");y[p+h]=t}else for(h=0;h<n;++h)y[p+h]=f[h];null!==e&&e.push(Sb,k);return k},Ld:8,readValueFromPointer:Ya,Nd(e){Sb(e)}})},G:(a,b,c)=>{c=H(c);if(2===b){var e=
mc;var f=nc;var h=oc;var n=k=>za[k>>1]}else 4===b&&(e=pc,f=qc,h=rc,n=k=>D[k>>2]);cb(a,{name:c,fromWireType:k=>{for(var p=D[k>>2],t,v=k+4,z=0;z<=p;++z){var A=k+4+z*b;if(z==p||0==n(A))v=e(v,A-v),void 0===t?t=v:(t+=String.fromCharCode(0),t+=v),v=A+b}Sb(k);return t},toWireType:(k,p)=>{if("string"!=typeof p)throw new I(`Cannot pass non-string to C++ string type ${c}`);var t=h(p),v=gd(4+t+b);D[v>>2]=t/b;f(p,v+4,t+b);null!==k&&k.push(Sb,v);return v},Ld:8,readValueFromPointer:Ya,Nd(k){Sb(k)}})},A:(a,b,c,
e,f,h)=>{Ua[a]={name:H(b),ne:K(c,e),Qd:K(f,h),se:[]}},i:(a,b,c,e,f,h,n,k,p,t)=>{Ua[a].se.push({He:H(b),Me:c,Ke:K(e,f),Le:h,Te:n,Se:K(k,p),Ue:t})},Yc:(a,b)=>{b=H(b);cb(a,{Ze:!0,name:b,Ld:0,fromWireType:()=>{},toWireType:()=>{}})},Xc:()=>1,Wc:()=>{throw Infinity;},Vc:(a,b,c)=>{a=bc(a);b=ec(b,"emval::as");return sc(b,c,a)},Uc:(a,b,c,e)=>{a=tc[a];b=bc(b);return a(null,b,c,e)},o:(a,b,c,e,f)=>{a=tc[a];b=bc(b);c=vc(c);return a(b,b[c],e,f)},e:ac,Tc:a=>{if(0===a)return Db(wc());a=vc(a);return Db(wc()[a])},
m:(a,b,c)=>{var e=yc(a,b),f=e.shift();a--;var h=Array(a);b=`methodCaller<(${e.map(n=>n.name).join(", ")}) => ${f.name}>`;return xc(ub(b,(n,k,p,t)=>{for(var v=0,z=0;z<a;++z)h[z]=e[z].readValueFromPointer(t+v),v+=e[z].Ld;n=1===c?zc(k,h):k.apply(n,h);return sc(f,p,n)}))},F:a=>{9<a&&($b[a+1]+=1)},E:()=>Db([]),v:a=>Db(vc(a)),Sc:()=>Db({}),k:a=>{var b=bc(a);Xa(b);ac(a)},z:(a,b,c)=>{a=bc(a);b=bc(b);c=bc(c);a[b]=c},h:(a,b)=>{a=ec(a,"_emval_take_value");a=a.readValueFromPointer(b);return Db(a)},Rc:(a,b,c,
e)=>{var f=(new Date).getFullYear(),h=(new Date(f,0,1)).getTimezoneOffset();f=(new Date(f,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(h,f);C[b>>2]=Number(h!=f);b=n=>{var k=Math.abs(n);return`UTC${0<=n?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(h);b=b(f);f<h?(hc(a,c,17),hc(b,e,17)):(hc(a,e,17),hc(b,c,17))},Qc:()=>performance.now(),Pc:a=>N.activeTexture(a),Oc:(a,b)=>{N.attachShader(Gc[a],Jc[b])},Nc:(a,b)=>{N.beginQuery(a,O[b])},Mc:(a,b)=>{N.Pd.beginQueryEXT(a,
O[b])},Lc:(a,b,c)=>{N.bindAttribLocation(Gc[a],b,c?kc(y,c):"")},Kc:(a,b)=>{35051==a?N.ke=b:35052==a&&(N.Ud=b);N.bindBuffer(a,Fc[b])},Jc:Vc,Ic:(a,b)=>{N.bindRenderbuffer(a,Ic[b])},Hc:(a,b)=>{N.bindSampler(a,Lc[b])},Gc:(a,b)=>{N.bindTexture(a,ia[b])},Fc:Wc,Ec:Wc,Dc:(a,b,c,e)=>N.blendColor(a,b,c,e),Cc:a=>N.blendEquation(a),Bc:(a,b)=>N.blendFunc(a,b),Ac:(a,b,c,e,f,h,n,k,p,t)=>N.blitFramebuffer(a,b,c,e,f,h,n,k,p,t),zc:(a,b,c,e)=>{2<=x.version?c&&b?N.bufferData(a,y,e,c,b):N.bufferData(a,b,e):N.bufferData(a,
c?y.subarray(c,c+b):b,e)},yc:(a,b,c,e)=>{2<=x.version?c&&N.bufferSubData(a,b,y,e,c):N.bufferSubData(a,b,y.subarray(e,e+c))},xc:a=>N.checkFramebufferStatus(a),wc:Xc,vc:Yc,uc:Zc,tc:(a,b,c,e)=>N.clientWaitSync(Mc[a],b,(c>>>0)+4294967296*e),sc:(a,b,c,e)=>{N.colorMask(!!a,!!b,!!c,!!e)},rc:a=>{N.compileShader(Jc[a])},qc:(a,b,c,e,f,h,n,k)=>{2<=x.version?N.Ud||!n?N.compressedTexImage2D(a,b,c,e,f,h,n,k):N.compressedTexImage2D(a,b,c,e,f,h,y,k,n):N.compressedTexImage2D(a,b,c,e,f,h,y.subarray(k,k+n))},pc:(a,
b,c,e,f,h,n,k,p)=>{2<=x.version?N.Ud||!k?N.compressedTexSubImage2D(a,b,c,e,f,h,n,k,p):N.compressedTexSubImage2D(a,b,c,e,f,h,n,y,p,k):N.compressedTexSubImage2D(a,b,c,e,f,h,n,y.subarray(p,p+k))},oc:(a,b,c,e,f)=>N.copyBufferSubData(a,b,c,e,f),nc:(a,b,c,e,f,h,n,k)=>N.copyTexSubImage2D(a,b,c,e,f,h,n,k),mc:()=>{var a=ha(Gc),b=N.createProgram();b.name=a;b.ie=b.ge=b.he=0;b.oe=1;Gc[a]=b;return a},lc:a=>{var b=ha(Jc);Jc[b]=N.createShader(a);return b},kc:a=>N.cullFace(a),jc:(a,b)=>{for(var c=0;c<a;c++){var e=
C[b+4*c>>2],f=Fc[e];f&&(N.deleteBuffer(f),f.name=0,Fc[e]=null,e==N.ke&&(N.ke=0),e==N.Ud&&(N.Ud=0))}},ic:(a,b)=>{for(var c=0;c<a;++c){var e=C[b+4*c>>2],f=Hc[e];f&&(N.deleteFramebuffer(f),f.name=0,Hc[e]=null)}},hc:a=>{if(a){var b=Gc[a];b?(N.deleteProgram(b),b.name=0,Gc[a]=null):Q||=1281}},gc:(a,b)=>{for(var c=0;c<a;c++){var e=C[b+4*c>>2],f=O[e];f&&(N.deleteQuery(f),O[e]=null)}},fc:(a,b)=>{for(var c=0;c<a;c++){var e=C[b+4*c>>2],f=O[e];f&&(N.Pd.deleteQueryEXT(f),O[e]=null)}},ec:(a,b)=>{for(var c=0;c<
a;c++){var e=C[b+4*c>>2],f=Ic[e];f&&(N.deleteRenderbuffer(f),f.name=0,Ic[e]=null)}},dc:(a,b)=>{for(var c=0;c<a;c++){var e=C[b+4*c>>2],f=Lc[e];f&&(N.deleteSampler(f),f.name=0,Lc[e]=null)}},cc:a=>{if(a){var b=Jc[a];b?(N.deleteShader(b),Jc[a]=null):Q||=1281}},bc:a=>{if(a){var b=Mc[a];b?(N.deleteSync(b),b.name=0,Mc[a]=null):Q||=1281}},ac:(a,b)=>{for(var c=0;c<a;c++){var e=C[b+4*c>>2],f=ia[e];f&&(N.deleteTexture(f),f.name=0,ia[e]=null)}},$b:$c,_b:$c,Zb:a=>{N.depthMask(!!a)},Yb:a=>N.disable(a),Xb:a=>{N.disableVertexAttribArray(a)},
Wb:(a,b,c)=>{N.drawArrays(a,b,c)},Vb:(a,b,c,e)=>{N.drawArraysInstanced(a,b,c,e)},Ub:(a,b,c,e,f)=>{N.re.drawArraysInstancedBaseInstanceWEBGL(a,b,c,e,f)},Tb:(a,b)=>{for(var c=ad[a],e=0;e<a;e++)c[e]=C[b+4*e>>2];N.drawBuffers(c)},Sb:(a,b,c,e)=>{N.drawElements(a,b,c,e)},Rb:(a,b,c,e,f)=>{N.drawElementsInstanced(a,b,c,e,f)},Qb:(a,b,c,e,f,h,n)=>{N.re.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,b,c,e,f,h,n)},Pb:(a,b,c,e,f,h)=>{N.drawElements(a,e,f,h)},Ob:a=>N.enable(a),Nb:a=>{N.enableVertexAttribArray(a)},
Mb:a=>N.endQuery(a),Lb:a=>{N.Pd.endQueryEXT(a)},Kb:(a,b)=>(a=N.fenceSync(a,b))?(b=ha(Mc),a.name=b,Mc[b]=a,b):0,Jb:()=>N.finish(),Ib:()=>N.flush(),Hb:(a,b,c,e)=>{N.framebufferRenderbuffer(a,b,c,Ic[e])},Gb:(a,b,c,e,f)=>{N.framebufferTexture2D(a,b,c,ia[e],f)},Fb:a=>N.frontFace(a),Eb:(a,b)=>{Sc(a,b,"createBuffer",Fc)},Db:(a,b)=>{Sc(a,b,"createFramebuffer",Hc)},Cb:(a,b)=>{Sc(a,b,"createQuery",O)},Bb:(a,b)=>{for(var c=0;c<a;c++){var e=N.Pd.createQueryEXT();if(!e){for(Q||=1282;c<a;)C[b+4*c++>>2]=0;break}var f=
ha(O);e.name=f;O[f]=e;C[b+4*c>>2]=f}},Ab:(a,b)=>{Sc(a,b,"createRenderbuffer",Ic)},zb:(a,b)=>{Sc(a,b,"createSampler",Lc)},yb:(a,b)=>{Sc(a,b,"createTexture",ia)},xb:bd,wb:bd,vb:a=>N.generateMipmap(a),ub:(a,b,c)=>{c?C[c>>2]=N.getBufferParameter(a,b):Q||=1281},tb:()=>{var a=N.getError()||Q;Q=0;return a},sb:(a,b)=>dd(a,b,2),rb:(a,b,c,e)=>{a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;C[e>>2]=a},qb:ed,pb:(a,b,c,e)=>{a=N.getProgramInfoLog(Gc[a]);
null===a&&(a="(unknown error)");b=0<b&&e?hc(a,e,b):0;c&&(C[c>>2]=b)},ob:(a,b,c)=>{if(c)if(a>=Ec)Q||=1281;else if(a=Gc[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),C[c>>2]=a.length+1;else if(35719==b){if(!a.ie){var e=N.getProgramParameter(a,35718);for(b=0;b<e;++b)a.ie=Math.max(a.ie,N.getActiveUniform(a,b).name.length+1)}C[c>>2]=a.ie}else if(35722==b){if(!a.ge)for(e=N.getProgramParameter(a,35721),b=0;b<e;++b)a.ge=Math.max(a.ge,N.getActiveAttrib(a,b).name.length+1);C[c>>2]=a.ge}else if(35381==
b){if(!a.he)for(e=N.getProgramParameter(a,35382),b=0;b<e;++b)a.he=Math.max(a.he,N.getActiveUniformBlockName(a,b).length+1);C[c>>2]=a.he}else C[c>>2]=N.getProgramParameter(a,b);else Q||=1281},nb:fd,mb:fd,lb:(a,b,c)=>{if(c){a=N.getQueryParameter(O[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;C[c>>2]=e}else Q||=1281},kb:(a,b,c)=>{if(c){a=N.Pd.getQueryObjectEXT(O[a],b);var e;"boolean"==typeof a?e=a?1:0:e=a;C[c>>2]=e}else Q||=1281},jb:(a,b,c)=>{c?C[c>>2]=N.getQuery(a,b):Q||=1281},ib:(a,b,c)=>{c?C[c>>2]=
N.Pd.getQueryEXT(a,b):Q||=1281},hb:(a,b,c)=>{c?C[c>>2]=N.getRenderbufferParameter(a,b):Q||=1281},gb:(a,b,c,e)=>{a=N.getShaderInfoLog(Jc[a]);null===a&&(a="(unknown error)");b=0<b&&e?hc(a,e,b):0;c&&(C[c>>2]=b)},fb:(a,b,c,e)=>{a=N.getShaderPrecisionFormat(a,b);C[c>>2]=a.rangeMin;C[c+4>>2]=a.rangeMax;C[e>>2]=a.precision},eb:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(Jc[a]),null===a&&(a="(unknown error)"),C[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(Jc[a]),C[c>>2]=a?a.length+1:0):C[c>>2]=N.getShaderParameter(Jc[a],
b):Q||=1281},db:jd,cb:kd,bb:(a,b)=>{b=b?kc(y,b):"";if(a=Gc[a]){var c=a,e=c.$d,f=c.we,h;if(!e){c.$d=e={};c.ve={};var n=N.getProgramParameter(c,35718);for(h=0;h<n;++h){var k=N.getActiveUniform(c,h);var p=k.name;k=k.size;var t=ld(p);t=0<t?p.slice(0,t):p;var v=c.oe;c.oe+=k;f[t]=[k,v];for(p=0;p<k;++p)e[v]=p,c.ve[v++]=t}}c=a.$d;e=0;f=b;h=ld(b);0<h&&(e=parseInt(b.slice(h+1))>>>0,f=b.slice(0,h));if((f=a.we[f])&&e<f[0]&&(e+=f[1],c[e]=c[e]||N.getUniformLocation(a,b)))return e}else Q||=1281;return-1},ab:(a,
b,c)=>{for(var e=ad[b],f=0;f<b;f++)e[f]=C[c+4*f>>2];N.invalidateFramebuffer(a,e)},$a:(a,b,c,e,f,h,n)=>{for(var k=ad[b],p=0;p<b;p++)k[p]=C[c+4*p>>2];N.invalidateSubFramebuffer(a,k,e,f,h,n)},_a:a=>N.isSync(Mc[a]),Za:a=>(a=ia[a])?N.isTexture(a):0,Ya:a=>N.lineWidth(a),Xa:a=>{a=Gc[a];N.linkProgram(a);a.$d=0;a.we={}},Wa:(a,b,c,e,f,h)=>{N.te.multiDrawArraysInstancedBaseInstanceWEBGL(a,C,b>>2,C,c>>2,C,e>>2,D,f>>2,h)},Va:(a,b,c,e,f,h,n,k)=>{N.te.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,C,b>>
2,c,C,e>>2,C,f>>2,C,h>>2,D,n>>2,k)},Ua:(a,b)=>{3317==a?Qc=b:3314==a&&(Rc=b);N.pixelStorei(a,b)},Ta:(a,b)=>{N.Pd.queryCounterEXT(O[a],b)},Sa:a=>N.readBuffer(a),Ra:(a,b,c,e,f,h,n)=>{if(2<=x.version)if(N.ke)N.readPixels(a,b,c,e,f,h,n);else{var k=md(h);n>>>=31-Math.clz32(k.BYTES_PER_ELEMENT);N.readPixels(a,b,c,e,f,h,k,n)}else(k=nd(h,f,c,e,n))?N.readPixels(a,b,c,e,f,h,k):Q||=1280},Qa:(a,b,c,e)=>N.renderbufferStorage(a,b,c,e),Pa:(a,b,c,e,f)=>N.renderbufferStorageMultisample(a,b,c,e,f),Oa:(a,b,c)=>{N.samplerParameterf(Lc[a],
b,c)},Na:(a,b,c)=>{N.samplerParameteri(Lc[a],b,c)},Ma:(a,b,c)=>{N.samplerParameteri(Lc[a],b,C[c>>2])},La:(a,b,c,e)=>N.scissor(a,b,c,e),Ka:(a,b,c,e)=>{for(var f="",h=0;h<b;++h){var n=(n=D[c+4*h>>2])?kc(y,n,e?D[e+4*h>>2]:void 0):"";f+=n}N.shaderSource(Jc[a],f)},Ja:(a,b,c)=>N.stencilFunc(a,b,c),Ia:(a,b,c,e)=>N.stencilFuncSeparate(a,b,c,e),Ha:a=>N.stencilMask(a),Ga:(a,b)=>N.stencilMaskSeparate(a,b),Fa:(a,b,c)=>N.stencilOp(a,b,c),Ea:(a,b,c,e)=>N.stencilOpSeparate(a,b,c,e),Da:(a,b,c,e,f,h,n,k,p)=>{if(2<=
x.version){if(N.Ud){N.texImage2D(a,b,c,e,f,h,n,k,p);return}if(p){var t=md(k);p>>>=31-Math.clz32(t.BYTES_PER_ELEMENT);N.texImage2D(a,b,c,e,f,h,n,k,t,p);return}}t=p?nd(k,n,e,f,p):null;N.texImage2D(a,b,c,e,f,h,n,k,t)},Ca:(a,b,c)=>N.texParameterf(a,b,c),Ba:(a,b,c)=>{N.texParameterf(a,b,G[c>>2])},Aa:(a,b,c)=>N.texParameteri(a,b,c),za:(a,b,c)=>{N.texParameteri(a,b,C[c>>2])},ya:(a,b,c,e,f)=>N.texStorage2D(a,b,c,e,f),xa:(a,b,c,e,f,h,n,k,p)=>{if(2<=x.version){if(N.Ud){N.texSubImage2D(a,b,c,e,f,h,n,k,p);return}if(p){var t=
md(k);N.texSubImage2D(a,b,c,e,f,h,n,k,t,p>>>31-Math.clz32(t.BYTES_PER_ELEMENT));return}}p=p?nd(k,n,f,h,p):null;N.texSubImage2D(a,b,c,e,f,h,n,k,p)},wa:(a,b)=>{N.uniform1f(U(a),b)},va:(a,b,c)=>{if(2<=x.version)b&&N.uniform1fv(U(a),G,c>>2,b);else{if(288>=b)for(var e=od[b],f=0;f<b;++f)e[f]=G[c+4*f>>2];else e=G.subarray(c>>2,c+4*b>>2);N.uniform1fv(U(a),e)}},ua:(a,b)=>{N.uniform1i(U(a),b)},ta:(a,b,c)=>{if(2<=x.version)b&&N.uniform1iv(U(a),C,c>>2,b);else{if(288>=b)for(var e=pd[b],f=0;f<b;++f)e[f]=C[c+4*
f>>2];else e=C.subarray(c>>2,c+4*b>>2);N.uniform1iv(U(a),e)}},sa:(a,b,c)=>{N.uniform2f(U(a),b,c)},ra:(a,b,c)=>{if(2<=x.version)b&&N.uniform2fv(U(a),G,c>>2,2*b);else{if(144>=b){b*=2;for(var e=od[b],f=0;f<b;f+=2)e[f]=G[c+4*f>>2],e[f+1]=G[c+(4*f+4)>>2]}else e=G.subarray(c>>2,c+8*b>>2);N.uniform2fv(U(a),e)}},qa:(a,b,c)=>{N.uniform2i(U(a),b,c)},pa:(a,b,c)=>{if(2<=x.version)b&&N.uniform2iv(U(a),C,c>>2,2*b);else{if(144>=b){b*=2;for(var e=pd[b],f=0;f<b;f+=2)e[f]=C[c+4*f>>2],e[f+1]=C[c+(4*f+4)>>2]}else e=
C.subarray(c>>2,c+8*b>>2);N.uniform2iv(U(a),e)}},oa:(a,b,c,e)=>{N.uniform3f(U(a),b,c,e)},na:(a,b,c)=>{if(2<=x.version)b&&N.uniform3fv(U(a),G,c>>2,3*b);else{if(96>=b){b*=3;for(var e=od[b],f=0;f<b;f+=3)e[f]=G[c+4*f>>2],e[f+1]=G[c+(4*f+4)>>2],e[f+2]=G[c+(4*f+8)>>2]}else e=G.subarray(c>>2,c+12*b>>2);N.uniform3fv(U(a),e)}},ma:(a,b,c,e)=>{N.uniform3i(U(a),b,c,e)},la:(a,b,c)=>{if(2<=x.version)b&&N.uniform3iv(U(a),C,c>>2,3*b);else{if(96>=b){b*=3;for(var e=pd[b],f=0;f<b;f+=3)e[f]=C[c+4*f>>2],e[f+1]=C[c+(4*
f+4)>>2],e[f+2]=C[c+(4*f+8)>>2]}else e=C.subarray(c>>2,c+12*b>>2);N.uniform3iv(U(a),e)}},ka:(a,b,c,e,f)=>{N.uniform4f(U(a),b,c,e,f)},ja:(a,b,c)=>{if(2<=x.version)b&&N.uniform4fv(U(a),G,c>>2,4*b);else{if(72>=b){var e=od[4*b],f=G;c>>=2;b*=4;for(var h=0;h<b;h+=4){var n=c+h;e[h]=f[n];e[h+1]=f[n+1];e[h+2]=f[n+2];e[h+3]=f[n+3]}}else e=G.subarray(c>>2,c+16*b>>2);N.uniform4fv(U(a),e)}},ia:(a,b,c,e,f)=>{N.uniform4i(U(a),b,c,e,f)},ha:(a,b,c)=>{if(2<=x.version)b&&N.uniform4iv(U(a),C,c>>2,4*b);else{if(72>=b){b*=
4;for(var e=pd[b],f=0;f<b;f+=4)e[f]=C[c+4*f>>2],e[f+1]=C[c+(4*f+4)>>2],e[f+2]=C[c+(4*f+8)>>2],e[f+3]=C[c+(4*f+12)>>2]}else e=C.subarray(c>>2,c+16*b>>2);N.uniform4iv(U(a),e)}},ga:(a,b,c,e)=>{if(2<=x.version)b&&N.uniformMatrix2fv(U(a),!!c,G,e>>2,4*b);else{if(72>=b){b*=4;for(var f=od[b],h=0;h<b;h+=4)f[h]=G[e+4*h>>2],f[h+1]=G[e+(4*h+4)>>2],f[h+2]=G[e+(4*h+8)>>2],f[h+3]=G[e+(4*h+12)>>2]}else f=G.subarray(e>>2,e+16*b>>2);N.uniformMatrix2fv(U(a),!!c,f)}},fa:(a,b,c,e)=>{if(2<=x.version)b&&N.uniformMatrix3fv(U(a),
!!c,G,e>>2,9*b);else{if(32>=b){b*=9;for(var f=od[b],h=0;h<b;h+=9)f[h]=G[e+4*h>>2],f[h+1]=G[e+(4*h+4)>>2],f[h+2]=G[e+(4*h+8)>>2],f[h+3]=G[e+(4*h+12)>>2],f[h+4]=G[e+(4*h+16)>>2],f[h+5]=G[e+(4*h+20)>>2],f[h+6]=G[e+(4*h+24)>>2],f[h+7]=G[e+(4*h+28)>>2],f[h+8]=G[e+(4*h+32)>>2]}else f=G.subarray(e>>2,e+36*b>>2);N.uniformMatrix3fv(U(a),!!c,f)}},ea:(a,b,c,e)=>{if(2<=x.version)b&&N.uniformMatrix4fv(U(a),!!c,G,e>>2,16*b);else{if(18>=b){var f=od[16*b],h=G;e>>=2;b*=16;for(var n=0;n<b;n+=16){var k=e+n;f[n]=h[k];
f[n+1]=h[k+1];f[n+2]=h[k+2];f[n+3]=h[k+3];f[n+4]=h[k+4];f[n+5]=h[k+5];f[n+6]=h[k+6];f[n+7]=h[k+7];f[n+8]=h[k+8];f[n+9]=h[k+9];f[n+10]=h[k+10];f[n+11]=h[k+11];f[n+12]=h[k+12];f[n+13]=h[k+13];f[n+14]=h[k+14];f[n+15]=h[k+15]}}else f=G.subarray(e>>2,e+64*b>>2);N.uniformMatrix4fv(U(a),!!c,f)}},da:a=>{a=Gc[a];N.useProgram(a);N.Ee=a},ca:(a,b)=>N.vertexAttrib1f(a,b),ba:(a,b)=>{N.vertexAttrib2f(a,G[b>>2],G[b+4>>2])},aa:(a,b)=>{N.vertexAttrib3f(a,G[b>>2],G[b+4>>2],G[b+8>>2])},$:(a,b)=>{N.vertexAttrib4f(a,G[b>>
2],G[b+4>>2],G[b+8>>2],G[b+12>>2])},_:(a,b)=>{N.vertexAttribDivisor(a,b)},Z:(a,b,c,e,f)=>{N.vertexAttribIPointer(a,b,c,e,f)},Y:(a,b,c,e,f,h)=>{N.vertexAttribPointer(a,b,c,!!e,f,h)},X:(a,b,c,e)=>N.viewport(a,b,c,e),W:(a,b,c,e)=>{N.waitSync(Mc[a],b,(c>>>0)+4294967296*e)},V:a=>{var b=y.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+1/c);e=Math.min(e,a+100663296);a:{e=(Math.min(2147483648,65536*Math.ceil(Math.max(a,e)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(e);
Ba();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},U:()=>x?x.handle:0,cd:(a,b)=>{var c=0;sd().forEach((e,f)=>{var h=b+c;f=D[a+4*f>>2]=h;for(h=0;h<e.length;++h)wa[f++]=e.charCodeAt(h);wa[f]=0;c+=e.length+1});return 0},bd:(a,b)=>{var c=sd();D[a>>2]=c.length;var e=0;c.forEach(f=>e+=f.length+1);D[b>>2]=e;return 0},ad:()=>52,M:function(){return 70},K:(a,b,c,e)=>{for(var f=0,h=0;h<c;h++){var n=D[b>>2],k=D[b+4>>2];b+=8;for(var p=0;p<k;p++){var t=y[n+p],v=td[a];0===t||10===t?((1===a?qa:ta)(kc(v)),
v.length=0):v.push(t)}f+=k}D[e>>2]=f;return 0},T:Vc,S:Xc,R:Yc,Q:Zc,D:ed,H:jd,P:kd,q:yd,C:zd,p:Ad,y:Bd,u:Cd,x:Dd,t:Ed,O:Fd,N:Gd},Z=function(){function a(c){Z=c.exports;ua=Z.dd;Ba();Hb=Z.gd;Da.unshift(Z.ed);Fa--;0==Fa&&(null!==Ia&&(clearInterval(Ia),Ia=null),Ja&&(c=Ja,Ja=null,c()));return Z}var b={a:Hd};Fa++;if(q.instantiateWasm)try{return q.instantiateWasm(b,a)}catch(c){ta(`Module.instantiateWasm callback failed with error: ${c}`),ca(c)}Ma??=q.locateFile?La("canvaskit.wasm")?"canvaskit.wasm":na+"canvaskit.wasm":
(new URL("canvaskit.wasm",import.meta.url)).href;Pa(b,function(c){a(c.instance)}).catch(ca);return{}}(),Lb=a=>(Lb=Z.fd)(a),gd=q._malloc=a=>(gd=q._malloc=Z.hd)(a),Sb=q._free=a=>(Sb=q._free=Z.id)(a),Id=(a,b)=>(Id=Z.jd)(a,b),Jd=a=>(Jd=Z.kd)(a),Kd=()=>(Kd=Z.ld)();q.dynCall_viji=(a,b,c,e,f)=>(q.dynCall_viji=Z.md)(a,b,c,e,f);q.dynCall_vijiii=(a,b,c,e,f,h,n)=>(q.dynCall_vijiii=Z.nd)(a,b,c,e,f,h,n);q.dynCall_viiiiij=(a,b,c,e,f,h,n,k)=>(q.dynCall_viiiiij=Z.od)(a,b,c,e,f,h,n,k);
q.dynCall_vij=(a,b,c,e)=>(q.dynCall_vij=Z.pd)(a,b,c,e);q.dynCall_jii=(a,b,c)=>(q.dynCall_jii=Z.qd)(a,b,c);q.dynCall_jiiiiii=(a,b,c,e,f,h,n)=>(q.dynCall_jiiiiii=Z.rd)(a,b,c,e,f,h,n);q.dynCall_jiiiiji=(a,b,c,e,f,h,n,k)=>(q.dynCall_jiiiiji=Z.sd)(a,b,c,e,f,h,n,k);q.dynCall_ji=(a,b)=>(q.dynCall_ji=Z.td)(a,b);q.dynCall_iijj=(a,b,c,e,f,h)=>(q.dynCall_iijj=Z.ud)(a,b,c,e,f,h);q.dynCall_jiji=(a,b,c,e,f)=>(q.dynCall_jiji=Z.vd)(a,b,c,e,f);
q.dynCall_viijii=(a,b,c,e,f,h,n)=>(q.dynCall_viijii=Z.wd)(a,b,c,e,f,h,n);q.dynCall_iiiiij=(a,b,c,e,f,h,n)=>(q.dynCall_iiiiij=Z.xd)(a,b,c,e,f,h,n);q.dynCall_iiiiijj=(a,b,c,e,f,h,n,k,p)=>(q.dynCall_iiiiijj=Z.yd)(a,b,c,e,f,h,n,k,p);q.dynCall_iiiiiijj=(a,b,c,e,f,h,n,k,p,t)=>(q.dynCall_iiiiiijj=Z.zd)(a,b,c,e,f,h,n,k,p,t);function Ad(a,b,c,e){var f=Kd();try{return Hb.get(a)(b,c,e)}catch(h){Jd(f);if(h!==h+0)throw h;Id(1,0)}}
function yd(a,b){var c=Kd();try{return Hb.get(a)(b)}catch(e){Jd(c);if(e!==e+0)throw e;Id(1,0)}}function Gd(a,b,c,e,f,h,n,k,p,t){var v=Kd();try{Hb.get(a)(b,c,e,f,h,n,k,p,t)}catch(z){Jd(v);if(z!==z+0)throw z;Id(1,0)}}function Dd(a,b,c,e){var f=Kd();try{Hb.get(a)(b,c,e)}catch(h){Jd(f);if(h!==h+0)throw h;Id(1,0)}}function Cd(a,b,c){var e=Kd();try{Hb.get(a)(b,c)}catch(f){Jd(e);if(f!==f+0)throw f;Id(1,0)}}function Bd(a,b){var c=Kd();try{Hb.get(a)(b)}catch(e){Jd(c);if(e!==e+0)throw e;Id(1,0)}}
function Ed(a,b,c,e,f){var h=Kd();try{Hb.get(a)(b,c,e,f)}catch(n){Jd(h);if(n!==n+0)throw n;Id(1,0)}}function zd(a,b,c){var e=Kd();try{return Hb.get(a)(b,c)}catch(f){Jd(e);if(f!==f+0)throw f;Id(1,0)}}function Fd(a,b,c,e,f,h,n){var k=Kd();try{Hb.get(a)(b,c,e,f,h,n)}catch(p){Jd(k);if(p!==p+0)throw p;Id(1,0)}}var Ld,Md;Ja=function Nd(){Ld||Od();Ld||(Ja=Nd)};function Od(){if(!(0<Fa)){if(!Md&&(Md=1,Qa(Ca),0<Fa))return;Ld||(Ld=1,q.calledRun=1,va||(Qa(Da),aa(q),q.onRuntimeInitialized?.(),Qa(Ea)))}}Od();
moduleRtn=da;


  return moduleRtn;
}
);
})();
export default CanvasKitInit;
