include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore

linter:
  rules:
    - directives_ordering
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
