name: dartpad_preview_shared
description: Shared modules for Dartpad Frontend.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.12.0-0"

resolution: workspace

dependencies:
  codemirror_dart: any
  dartpad: any
  logging: ^1.3.0
  path: ^1.9.1
  web: ^2.0.0

dev_dependencies:
  test: ^1.31.0
