steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/firebase', '.']
    dir: .cloud_build/firebase
images:
  - 'gcr.io/$PROJECT_ID/firebase'
tags: ['cloud-builders-community']
