name: package:dartpad_ui

permissions: read-all

on:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/dartpad_ui/
    strategy:
      fail-fast: false
      matrix:
        sdk: [ beta, main ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: ${{ matrix.sdk }}
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test test/probes
