runtime: python37
default_expiration: "0d 0h 10m"

handlers:
  - url: /pictures
    static_dir: pictures

  - url: /example
    static_dir: example

  - url: /scripts/assets/AssetManifest.json
    static_files: scripts/assets/AssetManifest.json
    upload: scripts/assets/AssetManifest\.json
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /scripts/assets/FontManifest.json
    static_files: scripts/assets/FontManifest.json
    upload: scripts/assets/FontManifest\.json
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /scripts/assets/fonts/MaterialIcons-Regular.otf
    static_files: scripts/assets/fonts/MaterialIcons-Regular.otf
    upload: /scripts/assets/fonts/MaterialIcons-Regular\.otf
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /scripts/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
    static_files: scripts/assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
    upload: /scripts/assets/packages/cupertino_icons/assets/CupertinoIcons\.ttf
    http_headers:
      Access-Control-Allow-Origin: "*"

  - url: /scripts
    static_dir: scripts
    expiration: "0d 0h 5m"

  - url: /styles
    static_dir: styles

  - url: /text-fonts
    static_dir: text-fonts

  - url: /packages/codemirror
    static_dir: packages/codemirror

  - url: /packages/dart-pad
    static_dir: packages/dart_pad

  - url: /packages/split
    static_dir: packages/split

  - url: /packages/mdc_web
    static_dir: packages/mdc_web

  - url: /third_party
    static_dir: third_party

  - url: .*
    script: auto

    # Enable for version == prod.
    secure: always
