application: dart-pad
version: prod
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "0d 3h"

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /pictures
  static_dir: pictures

- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: .*
  script: main.app
# Enable for version == prod.
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
