// Copyright (c) 2026, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:jaspr/dom.dart';

// TODO: move styles to components when next Jaspr version is released
/// Styles for client components, kept separate from their `package:web`
/// dependencies so Jaspr can evaluate them on the Dart VM.
/// This is a temporary solution until the next Jaspr version is released
List<StyleRule> get componentStyles => [
  css('.ide-shell').styles(
    display: .flex,
    width: 100.percent,
    height: 100.vh,
    flexDirection: .column,
    backgroundColor: const Color('#1e1e1e'),
  ),
  css('.workspace-shell').styles(
    display: .flex,
    minWidth: .zero,
    minHeight: .zero,
    flex: const Flex(grow: 1, basis: .zero),
  ),
  css('.file-tree-pane').styles(
    display: .flex,
    width: 240.px,
    minWidth: 240.px,
    minHeight: .zero,
    border: .only(
      right: .solid(color: const Color('#303030'), width: 1.px),
    ),
    overflow: .hidden,
    flexDirection: .column,
    backgroundColor: const Color('#181818'),
  ),
  css('.editor-host').styles(
    display: .flex,
    minWidth: .zero,
    minHeight: 0.px,
    overflow: .hidden,
    flexDirection: .column,
    flex: const Flex(grow: 1),
  ),
  css('.status-bar').styles(
    minHeight: 24.px,
    padding: .symmetric(horizontal: 10.px),
    border: .only(
      top: .solid(color: const Color('#303030'), width: 1.px),
    ),
    overflow: .hidden,
    color: const Color('#858585'),
    fontSize: 11.px,
    lineHeight: 24.px,
    textOverflow: .ellipsis,
    whiteSpace: .noWrap,
    backgroundColor: const Color('#181818'),
  ),
  css('.status-bar.error').styles(color: const Color('#ff8a8a')),
  css('.status-bar.warning').styles(color: const Color('#e5c07b')),
  css('.editor-tabs').styles(
    display: .flex,
    minHeight: 36.px,
    overflow: const .only(x: .auto, y: .hidden),
    flex: const .shrink(0),
    backgroundColor: const Color('#181818'),
  ),
  css('.editor-tab').styles(
    display: .flex,
    minWidth: 96.px,
    maxWidth: 180.px,
    padding: .only(left: 12.px, right: 8.px),
    border: .only(
      right: .solid(color: const Color('#303030'), width: 1.px),
      top: .solid(color: Colors.transparent, width: 2.px),
    ),
    cursor: .pointer,
    userSelect: .none,
    alignItems: .center,
    gap: .all(6.px),
    color: const Color('#a8a8a8'),
    backgroundColor: const Color('#181818'),
  ),
  css('.editor-tab.active').styles(
    border: .only(
      top: .solid(color: const Color('#7aa2f7'), width: 2.px),
    ),
    color: const Color('#e8e8e8'),
    backgroundColor: const Color('#1e1e1e'),
  ),
  css('.editor-tab:hover').styles(backgroundColor: const Color('#252525')),
  css('.editor-tab-name').styles(
    minWidth: .zero,
    overflow: .hidden,
    flex: const Flex(grow: 1, basis: .zero),
    fontFamily: const .list([FontFamily('Consolas'), FontFamilies.monospace]),
    fontSize: 12.px,
    textOverflow: .ellipsis,
    whiteSpace: .noWrap,
  ),
  css('.editor-tab-dirty-dot').styles(
    width: 7.px,
    height: 7.px,
    radius: .circular(4.px),
    flex: const .shrink(0),
    backgroundColor: const Color('#d4d4d4'),
  ),
  css('.editor-tab-action').styles(
    display: .flex,
    width: 18.px,
    height: 18.px,
    padding: .zero,
    border: .none,
    radius: .circular(4.px),
    cursor: .pointer,
    justifyContent: .center,
    alignItems: .center,
    color: const Color('#b8b8b8'),
    fontSize: 11.px,
    backgroundColor: Colors.transparent,
  ),
  css('.editor-tab-action:hover').styles(
    color: const Color('#ffffff'),
    backgroundColor: const Color('#3a3a3a'),
  ),
  css('.editor-tab-action.close:hover').styles(
    color: const Color('#ff8a8a'),
    backgroundColor: const Color('#4a2525'),
  ),
  css('.editor-stack').styles(
    position: const .relative(),
    minHeight: .zero,
    flex: const Flex(grow: 1, basis: .zero),
  ),
  css('.editor-tab-slot').styles(
    position: .absolute(top: 0.px, left: 0.px, right: 0.px, bottom: 0.px),
    opacity: 0,
    pointerEvents: .none,
  ),
  css('.editor-tab-slot.active').styles(
    position: const .relative(),
    height: 100.percent,
    opacity: 1,
    pointerEvents: .auto,
  ),
  css('.editor-container').styles(
    display: .flex,
    height: 100.percent,
    minWidth: .zero,
    overflow: .hidden,
    flex: const Flex(grow: 1, basis: .zero),
    backgroundColor: const Color('#1e1e1e'),
  ),
  css('.editor-container .cm-editor').styles(
    position: const .relative(),
    height: 100.percent,
    minWidth: .zero,
    flex: const Flex(grow: 1, basis: .zero),
  ),
  css('.editor-container .cm-scroller').styles(
    overflow: .auto,
    fontFamily: const .list([
      FontFamily('Cascadia Code'),
      FontFamily('Consolas'),
      FontFamilies.monospace,
    ]),
    fontSize: 14.px,
    raw: {'overscroll-behavior': 'none'},
  ),
  css('.file-tree').styles(
    display: .flex,
    height: 100.percent,
    minHeight: .zero,
    overflow: .hidden,
    flexDirection: .column,
    backgroundColor: const Color('#181818'),
  ),
  css('.file-tree-header').styles(
    display: .flex,
    minHeight: 38.px,
    padding: .symmetric(horizontal: 10.px),
    border: .only(
      bottom: .solid(color: const Color('#303030'), width: 1.px),
    ),
    justifyContent: .spaceBetween,
    alignItems: .center,
  ),
  css('.file-tree-title').styles(
    color: const Color('#d4d4d4'),
    fontSize: 11.px,
    fontWeight: FontWeight.w600,
    textTransform: .upperCase,
    letterSpacing: 0.7.px,
  ),
  css('.file-tree-toolbar').styles(display: .flex, gap: .all(4.px)),
  css('.file-tree-toolbar-button, .file-tree-action, .file-tree-disclosure').styles(
    display: .flex,
    padding: .zero,
    border: .none,
    radius: .circular(4.px),
    cursor: .pointer,
    justifyContent: .center,
    alignItems: .center,
    color: const Color('#a8a8a8'),
    backgroundColor: Colors.transparent,
  ),
  css('.file-tree-toolbar-button').styles(width: 24.px, height: 24.px),
  css('.file-tree-toolbar-button:hover, .file-tree-action:hover, .file-tree-disclosure:hover').styles(
    color: const Color('#ffffff'),
    backgroundColor: const Color('#353535'),
  ),
  css('.file-tree-toolbar-button:disabled, .file-tree-action:disabled').styles(
    opacity: 0.45,
    cursor: .defaultCursor,
  ),
  css('.file-tree-list').styles(
    minHeight: .zero,
    padding: .symmetric(vertical: 4.px),
    overflow: .auto,
    flex: const Flex(grow: 1, basis: .zero),
  ),
  css('.file-tree-list.drop-target').styles(
    shadow: .inset(
      offsetX: .zero,
      offsetY: .zero,
      blur: .zero,
      spread: 2.px,
      color: const Color('#7aa2f7'),
    ),
  ),
  css('.file-tree-list.busy').styles(cursor: .progress),
  css('.file-tree-item').styles(
    display: .flex,
    height: 25.px,
    padding: .only(
      left: const Unit.expression('calc(6px + var(--tree-depth) * 14px)'),
      right: 5.px,
    ),
    cursor: .pointer,
    userSelect: .none,
    alignItems: .center,
    gap: .all(5.px),
    color: const Color('#c5c5c5'),
    fontSize: 12.px,
  ),
  css('.file-tree-item:hover').styles(backgroundColor: const Color('#252525')),
  css('.file-tree-item.active').styles(
    color: const Color('#ffffff'),
    backgroundColor: const Color('#303747'),
  ),
  css('.file-tree-item.selected').styles(backgroundColor: const Color('#292929')),
  css('.file-tree-item.drop-target').styles(
    shadow: .inset(
      offsetX: .zero,
      offsetY: .zero,
      blur: .zero,
      spread: 1.px,
      color: const Color('#7aa2f7'),
    ),
  ),
  css('.file-tree-item.dragging').styles(opacity: 0.45),
  css('.file-tree-item.binary').styles(opacity: 0.58, cursor: .defaultCursor),
  css('.file-tree-disclosure').styles(
    width: 16.px,
    height: 20.px,
    flex: const .shrink(0),
    fontSize: 16.px,
  ),
  css('.file-tree-disclosure.spacer').styles(pointerEvents: .none),
  css('.file-tree-icon').styles(
    width: 16.px,
    height: 16.px,
    flex: const .shrink(0),
    color: const Color('#858585'),
    raw: const {'vertical-align': 'middle'},
  ),
  css('.file-tree-icon.file-icon-dart').styles(color: const Color('#5da9e9')),
  css('.file-tree-icon.file-icon-yaml').styles(color: const Color('#c586c0')),
  css('.file-tree-name').styles(
    minWidth: .zero,
    overflow: .hidden,
    flex: const Flex(grow: 1, basis: .zero),
    textOverflow: .ellipsis,
    whiteSpace: .noWrap,
  ),
  css('.file-tree-actions').styles(display: .none, gap: .all(2.px)),
  css('.file-tree-item:hover .file-tree-actions, .file-tree-item.active .file-tree-actions').styles(display: .flex),
  css('.file-tree-action').styles(
    width: 20.px,
    height: 20.px,
    flex: const .shrink(0),
  ),
  css('.file-tree-action.delete:hover').styles(
    color: const Color('#ff8a8a'),
    backgroundColor: const Color('#4a2525'),
  ),
  css('.file-tree-action.confirm:hover').styles(
    color: const Color('#9ece6a'),
    backgroundColor: const Color('#243a2a'),
  ),
  css('.file-tree-action-icon').styles(
    width: 12.px,
    height: 12.px,
  ),
  css('.file-tree-input-wrapper').styles(position: const .relative()),
  css('.file-tree-input').styles(
    height: 20.px,
    minWidth: .zero,
    padding: .symmetric(horizontal: 4.px),
    border: .all(color: const Color('#7aa2f7'), width: 1.px),
    outline: const Outline(style: .none),
    flex: const Flex(grow: 1, basis: .zero),
    color: const Color('#ffffff'),
    fontFamily: const .list([FontFamily('Consolas'), FontFamilies.monospace]),
    fontSize: 12.px,
    backgroundColor: const Color('#202020'),
  ),
  css('.file-tree-input.invalid').styles(
    border: .all(color: const Color('#ff6b6b'), width: 1.px),
  ),
  css('.file-tree-validation, .file-tree-error').styles(
    padding: .symmetric(horizontal: 8.px, vertical: 5.px),
    color: const Color('#ff9a9a'),
    fontSize: 11.px,
    backgroundColor: const Color('#351f1f'),
  ),
  css('.file-tree-validation').styles(
    margin: .only(left: 22.px, right: 6.px, bottom: 3.px),
    radius: .circular(3.px),
  ),
];
